import { ISelect } from "./types";

// ========== Blue ZONE ==========
const blueMapArray: ISelect[] = [
    { label: "Bellever Tor", value: "Bellever Tor" },
    { label: "Birchcopse", value: "Birchcopse" },
    { label: "Blackthorn Quarry", value: "Blackthorn Quarry" },
    { label: "Brent Knoll", value: "Brent Knoll" },
    { label: "Bryn Gorge", value: "Bryn Gorge" },
    { label: "Cedarcopse", value: "Cedarcopse" },
    { label: "Chillhag", value: "Chillhag" },
    { label: "Cracked Earth", value: "Cracked Earth" },
    { label: "Crose Gorge", value: "Crose Gorge" },
    { label: "Curlew Fen", value: "Curlew Fen" },
    { label: "Dewleaf Fen", value: "Dewleaf Fen" },
    { label: "Dryfield Meadow", value: "Dryfield Meadow" },
    { label: "Drywater Meadow", value: "Drywater Meadow" },
    { label: "Dusklight Fen", value: "Dusklight Fen" },
    { label: "Ferndell", value: "Ferndell" },
    { label: "Flynsdell", value: "Flynsdell" },
    { label: "Fog Fen", value: "Fog Fen" },
    { label: "Fractured Ground", value: "Fractured Ground" },
    { label: "Goffers Knoll", value: "Goffers Knoll" },
    { label: "Gwan Gorge", value: "Gwan Gorge" },
    { label: "Haldon Tor", value: "Haldon Tor" },
    { label: "Haytor", value: "Haytor" },
    { label: "Kilmar Tor", value: "Kilmar Tor" },
    { label: "Larchroad", value: "Larchroad" },
    { label: "Longmarch Meadow", value: "Longmarch Meadow" },
    { label: "Mase Knoll", value: "Mase Knoll" },
    { label: "Mawar Gorge", value: "Mawar Gorge" },
    { label: "Murky Fen", value: "Murky Fen" },
    { label: "Oakcopse", value: "Oakcopse" },
    { label: "Pen Fenair", value: "Pen Fenair" },
    { label: "Pen Garn", value: "Pen Garn" },
    { label: "Pen Gent", value: "Pen Gent" },
    { label: "Pen Kerrig", value: "Pen Kerrig" },
    { label: "Pen Uchaf", value: "Pen Uchaf" },
    { label: "Pinecopse", value: "Pinecopse" },
    { label: "Prospector's Hope", value: "Prospector's Hope" },
    { label: "Redlake", value: "Redlake" },
    { label: "Russerdell", value: "Russerdell" },
    { label: "Saddle Tor", value: "Saddle Tor" },
    { label: "Sandgust Cleft", value: "Sandgust Cleft" },
    { label: "Slimehag", value: "Slimehag" },
    { label: "Smoothfloor Cleft", value: "Smoothfloor Cleft" },
    { label: "Stagbourne", value: "Stagbourne" },
    { label: "Steelhide Meadow", value: "Steelhide Meadow" },
    { label: "Stinkhag", value: "Stinkhag" },
    { label: "VegAnimTest", value: "VegAnimTest" },
    { label: "Vixen Tor", value: "Vixen Tor" },
    { label: "Windripple Fen", value: "Windripple Fen" }
];

// ========== Yellow ZONE ==========
const yellowMapArray: ISelect[] = [
    { label: "Adrens Hill", value: "Adrens Hill" },
    { label: "Aspenwood", value: "Aspenwood" },
    { label: "Bonepool Marsh", value: "Bonepool Marsh" },
    { label: "Brons Hill", value: "Brons Hill" },
    { label: "Cairn Camain", value: "Cairn Camain" },
    { label: "Cairn Cloch", value: "Cairn Cloch" },
    { label: "Cairn Darg", value: "Cairn Darg" },
    { label: "Cairn Drain", value: "Cairn Drain" },
    { label: "Cairn Fidair", value: "Cairn Fidair" },
    { label: "Cairn Glascore", value: "Cairn Glascore" },
    { label: "Cairn Gorm", value: "Cairn Gorm" },
    { label: "Carns Hill", value: "Carns Hill" },
    { label: "Caulder Fissure", value: "Caulder Fissure" },
    { label: "Croker Hill", value: "Croker Hill" },
    { label: "Deeproot Wood", value: "Deeproot Wood" },
    { label: "Drownhorse Basin", value: "Drownhorse Basin" },
    { label: "Eldon Hill", value: "Eldon Hill" },
    { label: "Falsestep Marsh", value: "Falsestep Marsh" },
    { label: "Felniks Hill", value: "Felniks Hill" },
    { label: "Flatriver Trough", value: "Flatriver Trough" },
    { label: "Goldshimmer Plain", value: "Goldshimmer Plain" },
    { label: "Gutras Hill", value: "Gutras Hill" },
    { label: "Hornbeam Wood", value: "Hornbeam Wood" },
    { label: "Inis Mon", value: "Inis Mon" },
    { label: "Lazygrass Plain", value: "Lazygrass Plain" },
    { label: "Lewsdon Hill", value: "Lewsdon Hill" },
    { label: "Longshadow Plain", value: "Longshadow Plain" },
    { label: "Nightcreak Marsh", value: "Nightcreak Marsh" },
    { label: "Parchthroat Plain", value: "Parchthroat Plain" },
    { label: "Redstone Plain", value: "Redstone Plain" },
    { label: "Rowanwood", value: "Rowanwood" },
    { label: "Sleetwater Basin", value: "Sleetwater Basin" },
    { label: "Slithertail Marsh", value: "Slithertail Marsh" },
    { label: "Slowtree Plain", value: "Slowtree Plain" },
    { label: "Snapshaft Trough", value: "Snapshaft Trough" },
    { label: "Spindlewood", value: "Spindlewood" },
    { label: "Tharcal Fissure", value: "Tharcal Fissure" },
    { label: "Wanderlure Basin", value: "Wanderlure Basin" },
    { label: "Willow Wood", value: "Willow Wood" },
    { label: "Willowsigh Marsh", value: "Willowsigh Marsh" },
    { label: "Wispwhisper Marsh", value: "Wispwhisper Marsh" },
    { label: "Yew Wood", value: "Yew Wood" }
];

// ========== Red ZONE ==========
const redMapArray: ISelect[] = [
    { label: "Anklesnag Mire", value: "Anklesnag Mire" },
    { label: "Astolat", value: "Astolat" },
    { label: "Birken Fell", value: "Birken Fell" },
    { label: "Bowscale Fell", value: "Bowscale Fell" },
    { label: "Broken Fell", value: "Broken Fell" },
    { label: "Camlann", value: "Camlann" },
    { label: "Creag Dhor", value: "Creag Dhor" },
    { label: "Creag Garr", value: "Creag Garr" },
    { label: "Creag Meagir", value: "Creag Meagir" },
    { label: "Creag Morr", value: "Creag Morr" },
    { label: "Darkground Swamp", value: "Darkground Swamp" },
    { label: "Deadvein Gully", value: "Deadvein Gully" },
    { label: "Domhain Chasm", value: "Domhain Chasm" },
    { label: "Dusktree Swamp", value: "Dusktree Swamp" },
    { label: "Flimmerair Steppe", value: "Flimmerair Steppe" },
    { label: "Garrow Fell", value: "Garrow Fell" },
    { label: "Highbole Glen", value: "Highbole Glen" },
    { label: "Kindlegrass Steppe", value: "Kindlegrass Steppe" },
    { label: "Longtimber Glen", value: "Longtimber Glen" },
    { label: "Malag Crevasse", value: "Malag Crevasse" },
    { label: "Mardale", value: "Mardale" },
    { label: "Murkweald", value: "Murkweald" },
    { label: "Nightbloom Forest", value: "Nightbloom Forest" },
    { label: "Owlsong Glen", value: "Owlsong Glen" },
    { label: "Roastcorpse Steppe", value: "Roastcorpse Steppe" },
    { label: "Runnel Sink", value: "Runnel Sink" },
    { label: "Shiftshadow Expanse", value: "Shiftshadow Expanse" },
    { label: "Spectral Sump", value: "Spectral Sump" },
    { label: "Stumprot Swamp", value: "Stumprot Swamp" },
    { label: "Wyre Forest", value: "Wyre Forest" }
];

// ========== Black ZONE ==========
const blackMapArray: ISelect[] = [
    { label: 'Avalanche Incline', value: 'Avalanche Incline' },
    { label: 'Avalanche Ravine', value: 'Avalanche Ravine' },
    { label: 'Battlebrae Flatland', value: 'Battlebrae Flatland' },
    { label: 'Battlebrae Grassland', value: 'Battlebrae Grassland' },
    { label: 'Battlebrae Lake', value: 'Battlebrae Lake' },
    { label: 'Battlebrae Meadow', value: 'Battlebrae Meadow' },
    { label: 'Battlebrae Peaks', value: 'Battlebrae Peaks' },
    { label: 'Battlebrae Plain', value: 'Battlebrae Plain' },
    { label: 'Black Monastery', value: 'Black Monastery' },
    { label: 'Bleachskull Desert', value: 'Bleachskull Desert' },
    { label: 'Bleachskull Steppe', value: 'Bleachskull Steppe' },
    { label: 'Braemore Lowland', value: 'Braemore Lowland' },
    { label: 'Braemore Upland', value: 'Braemore Upland' },
    { label: 'Brambleshore Hinterlands', value: 'Brambleshore Hinterlands' },
    { label: 'Citadel of Ash', value: 'Citadel of Ash' },
    { label: 'Daemonium Keep', value: 'Daemonium Keep' },
    { label: 'Darkbough Snag', value: 'Darkbough Snag' },
    { label: 'Deadpine Forest', value: 'Deadpine Forest' },
    { label: 'Deathreach Priory', value: 'Deathreach Priory' },
    { label: 'Deathwisp Bog', value: 'Deathwisp Bog' },
    { label: 'Deathwisp Sink', value: 'Deathwisp Sink' },
    { label: 'Deepwood Copse', value: 'Deepwood Copse' },
    { label: 'Deepwood Dell', value: 'Deepwood Dell' },
    { label: 'Deepwood Gorge', value: 'Deepwood Gorge' },
    { label: 'Deepwood Pines', value: 'Deepwood Pines' },
    { label: 'Driftwood Glen', value: 'Driftwood Glen' },
    { label: 'Driftwood Hollow', value: 'Driftwood Hollow' },
    { label: 'Driftwood Vale', value: 'Driftwood Vale' },
    { label: 'Drownfield Course', value: 'Drownfield Course' },
    { label: 'Drownfield Fen', value: 'Drownfield Fen' },
    { label: 'Drownfield Mire', value: 'Drownfield Mire' },
    { label: 'Drownfield Quag', value: 'Drownfield Quag' },
    { label: 'Drownfield Rut', value: 'Drownfield Rut' },
    { label: 'Drownfield Sink', value: 'Drownfield Sink' },
    { label: 'Drownfield Slough', value: 'Drownfield Slough' },
    { label: 'Drownfield Wetland', value: 'Drownfield Wetland' },
    { label: 'Drybasin Oasis', value: 'Drybasin Oasis' },
    { label: 'Drybasin Riverbed', value: 'Drybasin Riverbed' },
    { label: 'Drytop Pillars', value: 'Drytop Pillars' },
    { label: 'Drytop Riverbed', value: 'Drytop Riverbed' },
    { label: 'Dryvein Confluence', value: 'Dryvein Confluence' },
    { label: 'Dryvein Cross', value: 'Dryvein Cross' },
    { label: 'Dryvein End', value: 'Dryvein End' },
    { label: 'Dryvein Oasis', value: 'Dryvein Oasis' },
    { label: 'Dryvein Plain', value: 'Dryvein Plain' },
    { label: 'Dryvein Riverbed', value: 'Dryvein Riverbed' },
    { label: 'Dryvein Steppe', value: 'Dryvein Steppe' },
    { label: 'Eldersleep', value: 'Eldersleep' },
    { label: 'Everwinter Crossing', value: 'Everwinter Crossing' },
    { label: 'Everwinter Expanse', value: 'Everwinter Expanse' },
    { label: 'Everwinter Gap', value: 'Everwinter Gap' },
    { label: 'Everwinter Gorge', value: 'Everwinter Gorge' },
    { label: 'Everwinter Incline', value: 'Everwinter Incline' },
    { label: 'Everwinter Passage', value: 'Everwinter Passage' },
    { label: 'Everwinter Peak', value: 'Everwinter Peak' },
    { label: 'Everwinter Plain', value: 'Everwinter Plain' },
    { label: 'Everwinter Reach', value: 'Everwinter Reach' },
    { label: 'Everwinter Shores', value: 'Everwinter Shores' },
    { label: 'Eye of the Forest', value: 'Eye of the Forest' },
    { label: 'Farshore Bay', value: 'Farshore Bay' },
    { label: 'Farshore Cape', value: 'Farshore Cape' },
    { label: 'Farshore Drylands', value: 'Farshore Drylands' },
    { label: 'Farshore Esker', value: 'Farshore Esker' },
    { label: 'Farshore Heath', value: 'Farshore Heath' },
    { label: 'Farshore Lagoon', value: 'Farshore Lagoon' },
    { label: 'Firesink Caldera', value: 'Firesink Caldera' },
    { label: 'Firesink Trench', value: 'Firesink Trench' },
    { label: 'Flammog Desolation', value: 'Flammog Desolation' },
    { label: 'Flammog Fork', value: 'Flammog Fork' },
    { label: 'Flammog Valley', value: 'Flammog Valley' },
    { label: 'Flatrock Cliffs', value: 'Flatrock Cliffs' },
    { label: 'Flatrock Plateau', value: 'Flatrock Plateau' },
    { label: 'Floatshoal Bight', value: 'Floatshoal Bight' },
    { label: 'Floatshoal Fissure', value: 'Floatshoal Fissure' },
    { label: 'Floatshoal Floe', value: 'Floatshoal Floe' },
    { label: 'Frostbite Chasm', value: 'Frostbite Chasm' },
    { label: 'Frostbite Mountain', value: 'Frostbite Mountain' },
    { label: 'Frostpeak Ascent', value: 'Frostpeak Ascent' },
    { label: 'Frostpeak Vista', value: 'Frostpeak Vista' },
    { label: 'Frostseep Crevasse', value: 'Frostseep Crevasse' },
    { label: 'Frostseep Ravine', value: 'Frostseep Ravine' },
    { label: 'Frostspring Passage', value: 'Frostspring Passage' },
    { label: 'Frostspring Volcano', value: 'Frostspring Volcano' },
    { label: 'Giantweald Copse', value: 'Giantweald Copse' },
    { label: 'Giantweald Dale', value: 'Giantweald Dale' },
    { label: 'Giantweald Edge', value: 'Giantweald Edge' },
    { label: 'Giantweald Glade', value: 'Giantweald Glade' },
    { label: 'Giantweald Roots', value: 'Giantweald Roots' },
    { label: 'Giantweald Woods', value: 'Giantweald Woods' },
    { label: 'Glacierbreak Summit', value: 'Glacierbreak Summit' },
    { label: 'Glacierfall Canyon', value: 'Glacierfall Canyon' },
    { label: 'Glacierfall Cross', value: 'Glacierfall Cross' },
    { label: 'Glacierfall Fissure', value: 'Glacierfall Fissure' },
    { label: 'Glacierfall Pass', value: 'Glacierfall Pass' },
    { label: 'Glacierfall Passage', value: 'Glacierfall Passage' },
    { label: 'Glacierfall Valley', value: 'Glacierfall Valley' },
    { label: 'Gravemound Brim', value: 'Gravemound Brim' },
    { label: 'Gravemound Cliffs', value: 'Gravemound Cliffs' },
    { label: 'Gravemound Hills', value: 'Gravemound Hills' },
    { label: 'Gravemound Knoll', value: 'Gravemound Knoll' },
    { label: 'Gravemound Slope', value: 'Gravemound Slope' },
    { label: 'Greenhollow Copse', value: 'Greenhollow Copse' },
    { label: 'Greenhollow Vale', value: 'Greenhollow Vale' },
    { label: 'Greenshore Bay', value: 'Greenshore Bay' },
    { label: 'Greenshore Peninsula', value: 'Greenshore Peninsula' },
    { label: 'Highstone Grassland', value: 'Highstone Grassland' },
    { label: 'Highstone Loch', value: 'Highstone Loch' },
    { label: 'Highstone Meadow', value: 'Highstone Meadow' },
    { label: 'Highstone Mound', value: 'Highstone Mound' },
    { label: 'Highstone Plains', value: 'Highstone Plains' },
    { label: 'Highstone Plateau', value: 'Highstone Plateau' },
    { label: 'Hightree Borderlands', value: 'Hightree Borderlands' },
    { label: 'Hightree Cliffs', value: 'Hightree Cliffs' },
    { label: 'Hightree Dale', value: 'Hightree Dale' },
    { label: 'Hightree Enclave', value: 'Hightree Enclave' },
    { label: 'Hightree Glade', value: 'Hightree Glade' },
    { label: 'Hightree Hillock', value: 'Hightree Hillock' },
    { label: 'Hightree Isle', value: 'Hightree Isle' },
    { label: 'Hightree Lake', value: 'Hightree Lake' },
    { label: 'Hightree Levee', value: 'Hightree Levee' },
    { label: 'Hightree Pass', value: 'Hightree Pass' },
    { label: 'Hightree Steep', value: 'Hightree Steep' },
    { label: 'Hightree Strand', value: 'Hightree Strand' },
    { label: 'Iceburn Cliffs', value: 'Iceburn Cliffs' },
    { label: 'Iceburn Firth', value: 'Iceburn Firth' },
    { label: 'Iceburn Peaks', value: 'Iceburn Peaks' },
    { label: 'Iceburn Tundra', value: 'Iceburn Tundra' },
    { label: 'Longfen Arms', value: 'Longfen Arms' },
    { label: 'Longfen Marsh', value: 'Longfen Marsh' },
    { label: 'Longfen Veins', value: 'Longfen Veins' },
    { label: 'Meltwater Bog', value: 'Meltwater Bog' },
    { label: 'Meltwater Channel', value: 'Meltwater Channel' },
    { label: 'Meltwater Delta', value: 'Meltwater Delta' },
    { label: 'Meltwater Sump', value: 'Meltwater Sump' },
    { label: 'Mudfoot Mounds', value: 'Mudfoot Mounds' },
    { label: 'Mudfoot Sump', value: 'Mudfoot Sump' },
    { label: 'Munten Fell', value: 'Munten Fell' },
    { label: 'Munten Rise', value: 'Munten Rise' },
    { label: 'Munten Tundra', value: 'Munten Tundra' },
    { label: 'Murdergulch Cross', value: 'Murdergulch Cross' },
    { label: 'Murdergulch Divide', value: 'Murdergulch Divide' },
    { label: 'Murdergulch Gap', value: 'Murdergulch Gap' },
    { label: 'Murdergulch Ravine', value: 'Murdergulch Ravine' },
    { label: 'Murdergulch Trail', value: 'Murdergulch Trail' },
    { label: 'Northstrand Beach', value: 'Northstrand Beach' },
    { label: 'Northstrand Dunes', value: 'Northstrand Dunes' },
    { label: 'Parchsand Cliffs', value: 'Parchsand Cliffs' },
    { label: 'Parchsand Drought', value: 'Parchsand Drought' },
    { label: 'Razorrock Bank', value: 'Razorrock Bank' },
    { label: 'Razorrock Chasm', value: 'Razorrock Chasm' },
    { label: 'Razorrock Edge', value: 'Razorrock Edge' },
    { label: 'Razorrock Gulch', value: 'Razorrock Gulch' },
    { label: 'Razorrock Passage', value: 'Razorrock Passage' },
    { label: 'Razorrock Ravine', value: 'Razorrock Ravine' },
    { label: 'Razorrock Valley', value: 'Razorrock Valley' },
    { label: 'Razorrock Verge', value: 'Razorrock Verge' },
    { label: 'Redtree Enclave', value: 'Redtree Enclave' },
    { label: 'Rivercopse Crossing', value: 'Rivercopse Crossing' },
    { label: 'Rivercopse Curve', value: 'Rivercopse Curve' },
    { label: 'Rivercopse Fount', value: 'Rivercopse Fount' },
    { label: 'Rivercopse Path', value: 'Rivercopse Path' },
    { label: 'Runnelvein Bog', value: 'Runnelvein Bog' },
    { label: 'Runnelvein Sink', value: 'Runnelvein Sink' },
    { label: 'Runnelvein Slough', value: 'Runnelvein Slough' },
    { label: 'Sandmount Ascent', value: 'Sandmount Ascent' },
    { label: 'Sandmount Desert', value: 'Sandmount Desert' },
    { label: 'Sandmount Esker', value: 'Sandmount Esker' },
    { label: 'Sandmount Strand', value: 'Sandmount Strand' },
    { label: 'Sandrift Coast', value: 'Sandrift Coast' },
    { label: 'Sandrift Dunes', value: 'Sandrift Dunes' },
    { label: 'Sandrift Expanse', value: 'Sandrift Expanse' },
    { label: 'Sandrift Fringe', value: 'Sandrift Fringe' },
    { label: 'Sandrift Prairie', value: 'Sandrift Prairie' },
    { label: 'Sandrift Shore', value: 'Sandrift Shore' },
    { label: 'Sandrift Steppe', value: 'Sandrift Steppe' },
    { label: 'Scuttlesink Marsh', value: 'Scuttlesink Marsh' },
    { label: 'Scuttlesink Mouth', value: 'Scuttlesink Mouth' },
    { label: 'Scuttlesink Pools', value: 'Scuttlesink Pools' },
    { label: 'Shaleheath Hills', value: 'Shaleheath Hills' },
    { label: 'Shaleheath Steep', value: 'Shaleheath Steep' },
    { label: 'Skullmarsh Lower', value: 'Skullmarsh Lower' },
    { label: 'Skullmarsh Upper', value: 'Skullmarsh Upper' },
    { label: 'Skylake Bridge', value: 'Skylake Bridge' },
    { label: 'Skylake Hinterlands', value: 'Skylake Hinterlands' },
    { label: 'Skysand Plateau', value: 'Skysand Plateau' },
    { label: 'Skysand Ridge', value: 'Skysand Ridge' },
    { label: 'Slakesands Canyon', value: 'Slakesands Canyon' },
    { label: 'Slakesands Mesa', value: 'Slakesands Mesa' },
    { label: 'Southgrove Copse', value: 'Southgrove Copse' },
    { label: 'Southgrove Escarp', value: 'Southgrove Escarp' },
    { label: 'Southgrove Thicket', value: 'Southgrove Thicket' },
    { label: 'Springsump Basin', value: 'Springsump Basin' },
    { label: 'Springsump Melt', value: 'Springsump Melt' },
    { label: 'Springsump Wetland', value: 'Springsump Wetland' },
    { label: 'Stonelake Fields', value: 'Stonelake Fields' },
    { label: 'Stonelake Hillock', value: 'Stonelake Hillock' },
    { label: 'Stonemouth Bay', value: 'Stonemouth Bay' },
    { label: 'Stonemouth Northbluff', value: 'Stonemouth Northbluff' },
    { label: 'Stonemouth Southbluff', value: 'Stonemouth Southbluff' },
    { label: 'Sunfang Approach', value: 'Sunfang Approach' },
    { label: 'Sunfang Cliffs', value: 'Sunfang Cliffs' },
    { label: 'Sunfang Dawn', value: 'Sunfang Dawn' },
    { label: 'Sunfang Ravine', value: 'Sunfang Ravine' },
    { label: 'Sunfang Wasteland', value: 'Sunfang Wasteland' },
    { label: 'Sunkenbough Spring', value: 'Sunkenbough Spring' },
    { label: 'Sunkenbough Woods', value: 'Sunkenbough Woods' },
    { label: 'Sunstrand Delta', value: 'Sunstrand Delta' },
    { label: 'Sunstrand Dunes', value: 'Sunstrand Dunes' },
    { label: 'Sunstrand Quicksands', value: 'Sunstrand Quicksands' },
    { label: 'Sunstrand Shoal', value: 'Sunstrand Shoal' },
    { label: 'Swiftsands Basin', value: 'Swiftsands Basin' },
    { label: 'Swiftsands Chaparral', value: 'Swiftsands Chaparral' },
    { label: 'Swiftsands Plain', value: 'Swiftsands Plain' },
    { label: 'Thirstwater Gully', value: 'Thirstwater Gully' },
    { label: 'Thirstwater Steppe', value: 'Thirstwater Steppe' },
    { label: 'Thirstwater Waste', value: 'Thirstwater Waste' },
    { label: 'Thunderrock Ascent', value: 'Thunderrock Ascent' },
    { label: 'Thunderrock Draw', value: 'Thunderrock Draw' },
    { label: 'Thunderrock Rapids', value: 'Thunderrock Rapids' },
    { label: 'Thunderrock Upland', value: 'Thunderrock Upland' },
    { label: 'Timberscar Copse', value: 'Timberscar Copse' },
    { label: 'Timberscar Dell', value: 'Timberscar Dell' },
    { label: 'Timberslope Bridge', value: 'Timberslope Bridge' },
    { label: 'Timberslope Dell', value: 'Timberslope Dell' },
    { label: 'Timberslope Grove', value: 'Timberslope Grove' },
    { label: 'Timbertop Dale', value: 'Timbertop Dale' },
    { label: 'Timbertop Escarp', value: 'Timbertop Escarp' },
    { label: 'Timbertop Wood', value: 'Timbertop Wood' },
    { label: 'Twinchannel Narrows', value: 'Twinchannel Narrows' },
    { label: 'Unhallowed Cloister', value: 'Unhallowed Cloister' },
    { label: 'Wailing Bulwark', value: 'Wailing Bulwark' },
    { label: 'Watchwood Bluffs', value: 'Watchwood Bluffs' },
    { label: 'Watchwood Grove', value: 'Watchwood Grove' },
    { label: 'Watchwood Lakeside', value: 'Watchwood Lakeside' },
    { label: 'Watchwood Precipice', value: 'Watchwood Precipice' },
    { label: 'Westweald Shore', value: 'Westweald Shore' },
    { label: 'Westweald Thicket', value: 'Westweald Thicket' },
    { label: 'Wetgrave Bog', value: 'Wetgrave Bog' },
    { label: 'Wetgrave Marsh', value: 'Wetgrave Marsh' },
    { label: 'Wetgrave Swale', value: 'Wetgrave Swale' },
    { label: 'Whitebank Cross', value: 'Whitebank Cross' },
    { label: 'Whitebank Descent', value: 'Whitebank Descent' },
    { label: 'Whitebank Ridge', value: 'Whitebank Ridge' },
    { label: 'Whitebank Shore', value: 'Whitebank Shore' },
    { label: 'Whitebank Stream', value: 'Whitebank Stream' },
    { label: 'Whitebank Wall', value: 'Whitebank Wall' },
    { label: 'Whitecliff Expanse', value: 'Whitecliff Expanse' },
    { label: 'Whitecliff Peak', value: 'Whitecliff Peak' },
    { label: 'Whitepeak Ascent', value: 'Whitepeak Ascent' },
    { label: 'Whitepeak Spring', value: 'Whitepeak Spring' },
    { label: 'Whitepeak Tundra', value: 'Whitepeak Tundra' },
    { label: 'Whitewall Pass', value: 'Whitewall Pass' },
    { label: 'Whitewall Ridge', value: 'Whitewall Ridge' },
    { label: 'Widemoor Delta', value: 'Widemoor Delta' },
    { label: 'Widemoor End', value: 'Widemoor End' },
    { label: 'Widemoor Estuary', value: 'Widemoor Estuary' },
    { label: 'Widemoor Fen', value: 'Widemoor Fen' },
    { label: 'Widemoor Flats', value: 'Widemoor Flats' },
    { label: 'Widemoor Hills', value: 'Widemoor Hills' },
    { label: 'Widemoor Pool', value: 'Widemoor Pool' },
    { label: 'Widemoor Shore', value: 'Widemoor Shore' },
    { label: 'Widemoor Woods', value: 'Widemoor Woods' },
    { label: 'Willowshade Hills', value: 'Willowshade Hills' },
    { label: 'Willowshade Icemarsh', value: 'Willowshade Icemarsh' },
    { label: 'Willowshade Lake', value: 'Willowshade Lake' },
    { label: 'Willowshade Mire', value: 'Willowshade Mire' },
    { label: 'Willowshade Pools', value: 'Willowshade Pools' },
    { label: 'Willowshade Sink', value: 'Willowshade Sink' },
    { label: 'Willowshade Wetlands', value: 'Willowshade Wetlands' },
    { label: 'Windgrass Border', value: 'Windgrass Border' },
    { label: 'Windgrass Coast', value: 'Windgrass Coast' },
    { label: 'Windgrass Fields', value: 'Windgrass Fields' },
    { label: 'Windgrass Gully', value: 'Windgrass Gully' },
    { label: 'Windgrass Precipice', value: 'Windgrass Precipice' },
    { label: 'Windgrass Rill', value: 'Windgrass Rill' },
    { label: 'Windgrass Terrace', value: 'Windgrass Terrace' }
];

// ========== Roads ZONE ==========
const roadsMapArray: ISelect[] = [
    { label: 'Cases-Ugumlos', value: 'Cases-Ugumlos' },
    { label: 'Casitos-Alieam', value: 'Casitos-Alieam' },
    { label: 'Casitos-Atinaum', value: 'Casitos-Atinaum' },
    { label: 'Casitos-Avaelum', value: 'Casitos-Avaelum' },
    { label: 'Casos-Aiagsum', value: 'Casos-Aiagsum' },
    { label: 'Casos-Aximam', value: 'Casos-Aximam' },
    { label: 'Casos-Ayosrom', value: 'Casos-Ayosrom' },
    { label: 'Casos-Uruxtum', value: 'Casos-Uruxtum' },
    { label: 'Cebitos-Aeaylum', value: 'Cebitos-Aeaylum' },
    { label: 'Cebos-Avemlum', value: 'Cebos-Avemlum' },
    { label: 'Ceres-Iooinum', value: 'Ceres-Iooinum' },
    { label: 'Ceritos-Avulsum', value: 'Ceritos-Avulsum' },
    { label: 'Ceros-Aeaylum', value: 'Ceros-Aeaylum' },
    { label: 'Cetitos-Aiayrom', value: 'Cetitos-Aiayrom' },
    { label: 'Cetitos-Avixnum', value: 'Cetitos-Avixnum' },
    { label: 'Cetitos-Aximam', value: 'Cetitos-Aximam' },
    { label: 'Cetos-Obaelos', value: 'Cetos-Obaelos' },
    { label: 'Cieites-Ugumlos', value: 'Cieites-Ugumlos' },
    { label: 'Cieitos-Avioaum', value: 'Cieitos-Avioaum' },
    { label: 'Cieitos-Ayosrom', value: 'Cieitos-Ayosrom' },
    { label: 'Cieitos-Obaelos', value: 'Cieitos-Obaelos' },
    { label: 'Cieitos-Otatrom', value: 'Cieitos-Otatrom' },
    { label: 'Cieos-Atatlum', value: 'Cieos-Atatlum' },
    { label: 'Cilitos-Opodam', value: 'Cilitos-Opodam' },
    { label: 'Cilos-Avioaum', value: 'Cilos-Avioaum' },
    { label: 'Cilos-Ofailos', value: 'Cilos-Ofailos' },
    { label: 'Cilos-Otatrom', value: 'Cilos-Otatrom' },
    { label: 'Conitos-Ofailos', value: 'Conitos-Ofailos' },
    { label: 'Conitos-Oxaeaum', value: 'Conitos-Oxaeaum' },
    { label: 'Conitos-Uruxtum', value: 'Conitos-Uruxtum' },
    { label: 'Conos-Avaelum', value: 'Conos-Avaelum' },
    { label: 'Coritos-Avemlum', value: 'Coritos-Avemlum' },
    { label: 'Coros-Aiayrom', value: 'Coros-Aiayrom' },
    { label: 'Coros-Alieam', value: 'Coros-Alieam' },
    { label: 'Coros-Atinaum', value: 'Coros-Atinaum' },
    { label: 'Coues-Exakrom', value: 'Coues-Exakrom' },
    { label: 'Couos-Ayayaum', value: 'Couos-Ayayaum' },
    { label: 'Couos-Opodam', value: 'Couos-Opodam' },
    { label: 'Curites-Exakrom', value: 'Curites-Exakrom' },
    { label: 'Curitos-Ayayaum', value: 'Curitos-Ayayaum' },
    { label: 'Curos-Avulsum', value: 'Curos-Avulsum' },
    { label: 'Cuyites-Iooinum', value: 'Cuyites-Iooinum' },
    { label: 'Cynitos-Aiagsum', value: 'Cynitos-Aiagsum' },
    { label: 'Cynitos-Atatlum', value: 'Cynitos-Atatlum' },
    { label: 'Cynos-Avixnum', value: 'Cynos-Avixnum' },
    { label: 'Cynos-Oxaeaum', value: 'Cynos-Oxaeaum' },
    { label: 'Fasites-Azazsum', value: 'Fasites-Azazsum' },
    { label: 'Fasitos-Atezsum', value: 'Fasitos-Atezsum' },
    { label: 'Fasitos-Oleraum', value: 'Fasitos-Oleraum' },
    { label: 'Fasitos-Oyuctum', value: 'Fasitos-Oyuctum' },
    { label: 'Fasos-Ayiotum', value: 'Fasos-Ayiotum' },
    { label: 'Febites-Opavun', value: 'Febites-Opavun' },
    { label: 'Febos-Acalun', value: 'Febos-Acalun' },
    { label: 'Ferites-Ohohtum', value: 'Ferites-Ohohtum' },
    { label: 'Feritos-Enomaum', value: 'Feritos-Enomaum' },
    { label: 'Feritos-Osinsum', value: 'Feritos-Osinsum' },
    { label: 'Feros-Oyuctum', value: 'Feros-Oyuctum' },
    { label: 'Fetos-Aiaylos', value: 'Fetos-Aiaylos' },
    { label: 'Fiees-Ohohtum', value: 'Fiees-Ohohtum' },
    { label: 'Fieites-Unavtum', value: 'Fieites-Unavtum' },
    { label: 'Fieos-Aiuttum', value: 'Fieos-Aiuttum' },
    { label: 'Fieos-Atezsum', value: 'Fieos-Atezsum' },
    { label: 'Files-Azazsum', value: 'Files-Azazsum' },
    { label: 'Filites-Izohun', value: 'Filites-Izohun' },
    { label: 'Filitos-Uzazlum', value: 'Filitos-Uzazlum' },
    { label: 'Filos-Abalam', value: 'Filos-Abalam' },
    { label: 'Firitos-Alodrom', value: 'Firitos-Alodrom' },
    { label: 'Firos-Aiavam', value: 'Firos-Aiavam' },
    { label: 'Firos-Enomaum', value: 'Firos-Enomaum' },
    { label: 'Firos-Ezatam', value: 'Firos-Ezatam' },
    { label: 'Firos-Osinsum', value: 'Firos-Osinsum' },
    { label: 'Fones-Opavun', value: 'Fones-Opavun' },
    { label: 'Fonitos-Amaurom', value: 'Fonitos-Amaurom' },
    { label: 'Fonos-Aiugsum', value: 'Fonos-Aiugsum' },
    { label: 'Fonos-Oleraum', value: 'Fonos-Oleraum' },
    { label: 'Foritos-Aiaylos', value: 'Foritos-Aiaylos' },
    { label: 'Foros-Egoisum', value: 'Foros-Egoisum' },
    { label: 'Foros-Uzazlum', value: 'Foros-Uzazlum' },
    { label: 'Foues-Aeaosum', value: 'Foues-Aeaosum' },
    { label: 'Fouitos-Aiuttum', value: 'Fouitos-Aiuttum' },
    { label: 'Fouos-Agosaum', value: 'Fouos-Agosaum' },
    { label: 'Fouos-Amaurom', value: 'Fouos-Amaurom' },
    { label: 'Furitos-Aiavam', value: 'Furitos-Aiavam' },
    { label: 'Fuyes-Izohun', value: 'Fuyes-Izohun' },
    { label: 'Fuyitos-Acalun', value: 'Fuyitos-Acalun' },
    { label: 'Fuyitos-Ayiotum', value: 'Fuyitos-Ayiotum' },
    { label: 'Fynes-Unavtum', value: 'Fynes-Unavtum' },
    { label: 'Fynites-Aeaosum', value: 'Fynites-Aeaosum' },
    { label: 'Fynitos-Abalam', value: 'Fynitos-Abalam' },
    { label: 'Fynitos-Agosaum', value: 'Fynitos-Agosaum' },
    { label: 'Fynitos-Aiugsum', value: 'Fynitos-Aiugsum' },
    { label: 'Fynitos-Egoisum', value: 'Fynitos-Egoisum' },
    { label: 'Fynitos-Ezatam', value: 'Fynitos-Ezatam' },
    { label: 'Fynos-Alodrom', value: 'Fynos-Alodrom' },
    { label: 'Hasitos-Avaolum', value: 'Hasitos-Avaolum' },
    { label: 'Hasitos-Umayaum', value: 'Hasitos-Umayaum' },
    { label: 'Hasos-Agoitum', value: 'Hasos-Agoitum' },
    { label: 'Hasos-Ayousum', value: 'Hasos-Ayousum' },
    { label: 'Hasos-Inayaum', value: 'Hasos-Inayaum' },
    { label: 'Hasos-Iuimaum', value: 'Hasos-Iuimaum' },
    { label: 'Hasos-Osuorom', value: 'Hasos-Osuorom' },
    { label: 'Hebes-Ouaylos', value: 'Hebes-Ouaylos' },
    { label: 'Hebites-Exemrom', value: 'Hebites-Exemrom' },
    { label: 'Hebitos-Atontum', value: 'Hebitos-Atontum' },
    { label: 'Hebos-Ulamsum', value: 'Hebos-Ulamsum' },
    { label: 'Heritos-Exozlos', value: 'Heritos-Exozlos' },
    { label: 'Heritos-Eyoztum', value: 'Heritos-Eyoztum' },
    { label: 'Heritos-Inayaum', value: 'Heritos-Inayaum' },
    { label: 'Heros-Atoyam', value: 'Heros-Atoyam' },
    { label: 'Hetitos-Iuaerom', value: 'Hetitos-Iuaerom' },
    { label: 'Hieos-Aiigaum', value: 'Hieos-Aiigaum' },
    { label: 'Hieos-Avaolum', value: 'Hieos-Avaolum' },
    { label: 'Hiles-Izizaum', value: 'Hiles-Izizaum' },
    { label: 'Hilites-Ugumtum', value: 'Hilites-Ugumtum' },
    { label: 'Hilitos-Aiigaum', value: 'Hilitos-Aiigaum' },
    { label: 'Hilitos-Osuorom', value: 'Hilitos-Osuorom' },
    { label: 'Hiros-Exozlos', value: 'Hiros-Exozlos' },
    { label: 'Hiros-Iuaerom', value: 'Hiros-Iuaerom' },
    { label: 'Honites-Izizaum', value: 'Honites-Izizaum' },
    { label: 'Honitos-Uxeulum', value: 'Honitos-Uxeulum' },
    { label: 'Honos-Oyezam', value: 'Honos-Oyezam' },
    { label: 'Honos-Umayaum', value: 'Honos-Umayaum' },
    { label: 'Horos-Ohenlum', value: 'Horos-Ohenlum' },
    { label: 'Hures-Ugumtum', value: 'Hures-Ugumtum' },
    { label: 'Hurites-Ieatun', value: 'Hurites-Ieatun' },
    { label: 'Hurites-Ouaylos', value: 'Hurites-Ouaylos' },
    { label: 'Huritos-Iuimaum', value: 'Huritos-Iuimaum' },
    { label: 'Huritos-Oiaelos', value: 'Huritos-Oiaelos' },
    { label: 'Huros-Atontum', value: 'Huros-Atontum' },
    { label: 'Huyes-Ogozlum', value: 'Huyes-Ogozlum' },
    { label: 'Huyitos-Agoitum', value: 'Huyitos-Agoitum' },
    { label: 'Huyitos-Ohenlum', value: 'Huyitos-Ohenlum' },
    { label: 'Huyos-Eyoztum', value: 'Huyos-Eyoztum' },
    { label: 'Huyos-Uxeulum', value: 'Huyos-Uxeulum' },
    { label: 'Hynes-Exemrom', value: 'Hynes-Exemrom' },
    { label: 'Hynes-Ieatun', value: 'Hynes-Ieatun' },
    { label: 'Hynites-Ogozlum', value: 'Hynites-Ogozlum' },
    { label: 'Hynitos-Atoyam', value: 'Hynitos-Atoyam' },
    { label: 'Hynitos-Ayousum', value: 'Hynitos-Ayousum' },
    { label: 'Hynitos-Oyezam', value: 'Hynitos-Oyezam' },
    { label: 'Hynitos-Ulamsum', value: 'Hynitos-Ulamsum' },
    { label: 'Hynos-Oiaelos', value: 'Hynos-Oiaelos' },
    { label: 'Oasitos-Aoeuam', value: 'Oasitos-Aoeuam' },
    { label: 'Oasos-Eraerom', value: 'Oasos-Eraerom' },
    { label: 'Oasos-Uromlum', value: 'Oasos-Uromlum' },
    { label: 'Oebitos-Eraerom', value: 'Oebitos-Eraerom' },
    { label: 'Oebitos-Oyozam', value: 'Oebitos-Oyozam' },
    { label: 'Oebos-Ixakaum', value: 'Oebos-Ixakaum' },
    { label: 'Oeritos-Ecunsum', value: 'Oeritos-Ecunsum' },
    { label: 'Oeritos-Oyexlos', value: 'Oeritos-Oyexlos' },
    { label: 'Oetos-Ofailos', value: 'Oetos-Ofailos' },
    { label: 'Oetos-Oyexlos', value: 'Oetos-Oyexlos' },
    { label: 'Oieitos-Ixakaum', value: 'Oieitos-Ixakaum' },
    { label: 'Oieos-Umiutum', value: 'Oieos-Umiutum' },
    { label: 'Oires-Oloblum', value: 'Oires-Oloblum' },
    { label: 'Oiritos-Eramtum', value: 'Oiritos-Eramtum' },
    { label: 'Oiros-Alaiam', value: 'Oiros-Alaiam' },
    { label: 'Oonitos-Umiutum', value: 'Oonitos-Umiutum' },
    { label: 'Ooros-Ataltum', value: 'Ooros-Ataltum' },
    { label: 'Ooros-Ecunsum', value: 'Ooros-Ecunsum' },
    { label: 'Oouitos-Alaiam', value: 'Oouitos-Alaiam' },
    { label: 'Oures-Araosum', value: 'Oures-Araosum' },
    { label: 'Ouritos-Ataltum', value: 'Ouritos-Ataltum' },
    { label: 'Ouritos-Ofailos', value: 'Ouritos-Ofailos' },
    { label: 'Ouyos-Aoeuam', value: 'Ouyos-Aoeuam' },
    { label: 'Oynites-Araosum', value: 'Oynites-Araosum' },
    { label: 'Oynites-Oloblum', value: 'Oynites-Oloblum' },
    { label: 'Oynitos-Uromlum', value: 'Oynitos-Uromlum' },
    { label: 'Oynos-Eramtum', value: 'Oynos-Eramtum' },
    { label: 'Oynos-Oyozam', value: 'Oynos-Oyozam' },
    { label: 'Pasos-Avosam', value: 'Pasos-Avosam' },
    { label: 'Pebos-Avosrom', value: 'Pebos-Avosrom' },
    { label: 'Peritos-Avosam', value: 'Peritos-Avosam' },
    { label: 'Peritos-Oconun', value: 'Peritos-Oconun' },
    { label: 'Peros-Aiataum', value: 'Peros-Aiataum' },
    { label: 'Petitos-Amayam', value: 'Petitos-Amayam' },
    { label: 'Petitos-Avosrom', value: 'Petitos-Avosrom' },
    { label: 'Petos-Aietam', value: 'Petos-Aietam' },
    { label: 'Pieos-Eterrom', value: 'Pieos-Eterrom' },
    { label: 'Pieos-Ofairom', value: 'Pieos-Ofairom' },
    { label: 'Pilitos-Eterrom', value: 'Pilitos-Eterrom' },
    { label: 'Pirites-Unatam', value: 'Pirites-Unatam' },
    { label: 'Piritos-Ofavam', value: 'Piritos-Ofavam' },
    { label: 'Piritos-Opabrom', value: 'Piritos-Opabrom' },
    { label: 'Ponitos-Aiayrom', value: 'Ponitos-Aiayrom' },
    { label: 'Poros-Aiayrom', value: 'Poros-Aiayrom' },
    { label: 'Poros-Oconun', value: 'Poros-Oconun' },
    { label: 'Poues-Unatam', value: 'Poues-Unatam' },
    { label: 'Pouitos-Ofairom', value: 'Pouitos-Ofairom' },
    { label: 'Pures-Ouozlum', value: 'Pures-Ouozlum' },
    { label: 'Puros-Amayam', value: 'Puros-Amayam' },
    { label: 'Puros-Ofavam', value: 'Puros-Ofavam' },
    { label: 'Puyitos-Aiataum', value: 'Puyitos-Aiataum' },
    { label: 'Pynites-Ouozlum', value: 'Pynites-Ouozlum' },
    { label: 'Pynitos-Aietam', value: 'Pynitos-Aietam' },
    { label: 'Pynos-Opabrom', value: 'Pynos-Opabrom' },
    { label: 'Qiient-Al-Nusom', value: 'Qiient-ANusom' },
    { label: 'Qiient-Al-Odesum', value: 'Qiient-AOdesum' },
    { label: 'Qiient-Al-Qinsis', value: 'Qiient-AQinsis' },
    { label: 'Qiient-Al-Tersas', value: 'Qiient-ATersas' },
    { label: 'Qiient-Al-Viesis', value: 'Qiient-AViesis' },
    { label: 'Qiient-Al-Vynsis', value: 'Qiient-AVynsis' },
    { label: 'Qiient-Et-Nusas', value: 'Qiient-ENusas' },
    { label: 'Qiient-Et-Odetis', value: 'Qiient-EOdetis' },
    { label: 'Qiient-Et-Qinsum', value: 'Qiient-EQinsum' },
    { label: 'Qiient-Et-Tertum', value: 'Qiient-ETertum' },
    { label: 'Qiient-In-Nutis', value: 'Qiient-INutis' },
    { label: 'Qiient-In-Odetum', value: 'Qiient-IOdetum' },
    { label: 'Qiient-In-Qinsis', value: 'Qiient-IQinsis' },
    { label: 'Qiient-In-Tersom', value: 'Qiient-ITersom' },
    { label: 'Qiient-In-Viesis', value: 'Qiient-IViesis' },
    { label: 'Qiient-In-Vyntum', value: 'Qiient-IVyntum' },
    { label: 'Qiient-Nutis', value: 'Qiient-Nutis' },
    { label: 'Qiient-Oc-Odetum', value: 'Qiient-OOdetum' },
    { label: 'Qiient-Odesas', value: 'Qiient-Odesas' },
    { label: 'Qiient-Qi-Nusom', value: 'Qiient-QNusom' },
    { label: 'Qiient-Qi-Odesas', value: 'Qiient-QOdesas' },
    { label: 'Qiient-Qi-Tersas', value: 'Qiient-QTersas' },
    { label: 'Qiient-Qi-Vynsis', value: 'Qiient-QVynsis' },
    { label: 'Qiient-Qinsum', value: 'Qiient-Qinsum' },
    { label: 'Qiient-Sa-Odetis', value: 'Qiient-SOdetis' },
    { label: 'Qiient-Si-Nusas', value: 'Qiient-SNusas' },
    { label: 'Qiient-Si-Odesum', value: 'Qiient-SOdesum' },
    { label: 'Qiient-Si-Tertum', value: 'Qiient-STertum' },
    { label: 'Qiient-Tersom', value: 'Qiient-Tersom' },
    { label: 'Qiient-Vyntum', value: 'Qiient-Vyntum' },
    { label: 'Qiitun-Al-Duosum', value: 'Qiitun-ADuosum' },
    { label: 'Qiitun-Duosum', value: 'Qiitun-Duosum' },
    { label: 'Qiitun-Et-Vietis', value: 'Qiitun-EVietis' },
    { label: 'Qiitun-Et-Vynsom', value: 'Qiitun-EVynsom' },
    { label: 'Qiitun-Si-Vynsom', value: 'Qiitun-SVynsom' },
    { label: 'Qiitun-Vietis', value: 'Qiitun-Vietis' },
    { label: 'Quaent-Al-Nusis', value: 'Quaent-ANusis' },
    { label: 'Quaent-Al-Odesum', value: 'Quaent-AOdesum' },
    { label: 'Quaent-Al-Qintis', value: 'Quaent-AQintis' },
    { label: 'Quaent-Al-Tersis', value: 'Quaent-ATersis' },
    { label: 'Quaent-Al-Viesom', value: 'Quaent-AViesom' },
    { label: 'Quaent-Al-Vynsum', value: 'Quaent-AVynsum' },
    { label: 'Quaent-In-Nusis', value: 'Quaent-INusis' },
    { label: 'Quaent-In-Odesum', value: 'Quaent-IOdesum' },
    { label: 'Quaent-Qintis', value: 'Quaent-Qintis' },
    { label: 'Quaent-Tersis', value: 'Quaent-Tersis' },
    { label: 'Quaent-Viesom', value: 'Quaent-Viesom' },
    { label: 'Quaent-Vynsum', value: 'Quaent-Vynsum' },
    { label: 'Quatun-Et-Nusas', value: 'Quatun-ENusas' },
    { label: 'Quatun-Et-Odetum', value: 'Quatun-EOdetum' },
    { label: 'Quatun-Nusas', value: 'Quatun-Nusas' },
    { label: 'Quatun-Odetum', value: 'Quatun-Odetum' },
    { label: 'Sases-Aoarsum', value: 'Sases-Aoarsum' },
    { label: 'Sases-Avuotum', value: 'Sases-Avuotum' },
    { label: 'Sasitos-Oyarlum', value: 'Sasitos-Oyarlum' },
    { label: 'Sasitos-Ugersum', value: 'Sasitos-Ugersum' },
    { label: 'Sasitos-Umogaum', value: 'Sasitos-Umogaum' },
    { label: 'Sasos-Abizaum', value: 'Sasos-Abizaum' },
    { label: 'Sasos-Egeylos', value: 'Sasos-Egeylos' },
    { label: 'Sasos-Oiozlum', value: 'Sasos-Oiozlum' },
    { label: 'Sebos-Avoirom', value: 'Sebos-Avoirom' },
    { label: 'Sebos-Oyohun', value: 'Sebos-Oyohun' },
    { label: 'Sebos-Ugersum', value: 'Sebos-Ugersum' },
    { label: 'Secent-Al-Duosom', value: 'Secent-ADuosom' },
    { label: 'Secent-Al-Nutum', value: 'Secent-ANutum' },
    { label: 'Secent-Al-Odetis', value: 'Secent-AOdetis' },
    { label: 'Secent-Al-Qinsom', value: 'Secent-AQinsom' },
    { label: 'Secent-Al-Tersum', value: 'Secent-ATersum' },
    { label: 'Secent-Al-Viesum', value: 'Secent-AViesum' },
    { label: 'Secent-Duosom', value: 'Secent-Duosom' },
    { label: 'Secent-Et-Odesis', value: 'Secent-EOdesis' },
    { label: 'Secent-Et-Qinsas', value: 'Secent-EQinsas' },
    { label: 'Secent-Et-Vyntum', value: 'Secent-EVyntum' },
    { label: 'Secent-In-Tersum', value: 'Secent-ITersum' },
    { label: 'Secent-Nutum', value: 'Secent-Nutum' },
    { label: 'Secent-Odesom', value: 'Secent-Odesom' },
    { label: 'Secent-Qi-Odesom', value: 'Secent-QOdesom' },
    { label: 'Secent-Qi-Qinsom', value: 'Secent-QQinsom' },
    { label: 'Secent-Sa-Odesis', value: 'Secent-SOdesis' },
    { label: 'Secent-Si-Odetis', value: 'Secent-SOdetis' },
    { label: 'Secent-Si-Qinsas', value: 'Secent-SQinsas' },
    { label: 'Secent-Viesum', value: 'Secent-Viesum' },
    { label: 'Secent-Vyntum', value: 'Secent-Vyntum' },
    { label: 'Sectun-Al-Vyntis', value: 'Sectun-AVyntis' },
    { label: 'Sectun-Et-Tersas', value: 'Sectun-ETersas' },
    { label: 'Sectun-In-Odesis', value: 'Sectun-IOdesis' },
    { label: 'Sectun-In-Qinsom', value: 'Sectun-IQinsom' },
    { label: 'Sectun-In-Vyntis', value: 'Sectun-IVyntis' },
    { label: 'Sectun-Oc-Odesis', value: 'Sectun-OOdesis' },
    { label: 'Sectun-Qinsom', value: 'Sectun-Qinsom' },
    { label: 'Sectun-Tersas', value: 'Sectun-Tersas' },
    { label: 'Seritos-Egeylos', value: 'Seritos-Egeylos' },
    { label: 'Seritos-Onaytum', value: 'Seritos-Onaytum' },
    { label: 'Setent-Al-Duosas', value: 'Setent-ADuosas' },
    { label: 'Setent-Al-Qinsum', value: 'Setent-AQinsum' },
    { label: 'Setent-Al-Vietis', value: 'Setent-AVietis' },
    { label: 'Setent-Duosas', value: 'Setent-Duosas' },
    { label: 'Setent-Et-Nusum', value: 'Setent-ENusum' },
    { label: 'Setent-Et-Qintis', value: 'Setent-EQintis' },
    { label: 'Setent-In-Qinsum', value: 'Setent-IQinsum' },
    { label: 'Setent-Nusum', value: 'Setent-Nusum' },
    { label: 'Setent-Qintis', value: 'Setent-Qintis' },
    { label: 'Setent-Vietis', value: 'Setent-Vietis' },
    { label: 'Setitos-Obobrom', value: 'Setitos-Obobrom' },
    { label: 'Setos-Aiaitum', value: 'Setos-Aiaitum' },
    { label: 'Setos-Avamsum', value: 'Setos-Avamsum' },
    { label: 'Settun-Al-Nusis', value: 'Settun-ANusis' },
    { label: 'Settun-Al-Odetum', value: 'Settun-AOdetum' },
    { label: 'Settun-Al-Tersom', value: 'Settun-ATersom' },
    { label: 'Settun-Al-Vynsis', value: 'Settun-AVynsis' },
    { label: 'Settun-Et-Odetum', value: 'Settun-EOdetum' },
    { label: 'Settun-In-Nusis', value: 'Settun-INusis' },
    { label: 'Settun-In-Odetum', value: 'Settun-IOdetum' },
    { label: 'Settun-Odetum', value: 'Settun-Odetum' },
    { label: 'Settun-Tersom', value: 'Settun-Tersom' },
    { label: 'Settun-Vynsis', value: 'Settun-Vynsis' },
    { label: 'Sieos-Ofugtum', value: 'Sieos-Ofugtum' },
    { label: 'Silitos-Abizaum', value: 'Silitos-Abizaum' },
    { label: 'Silos-Apenlum', value: 'Silos-Apenlum' },
    { label: 'Silos-Oyarlum', value: 'Silos-Oyarlum' },
    { label: 'Siritos-Avoirom', value: 'Siritos-Avoirom' },
    { label: 'Siritos-Oyohun', value: 'Siritos-Oyohun' },
    { label: 'Siros-Obobrom', value: 'Siros-Obobrom' },
    { label: 'Siros-Ofurlos', value: 'Siros-Ofurlos' },
    { label: 'Sonitos-Ayailos', value: 'Sonitos-Ayailos' },
    { label: 'Soritos-Aiaitum', value: 'Soritos-Aiaitum' },
    { label: 'Soritos-Apenlum', value: 'Soritos-Apenlum' },
    { label: 'Soritos-Avamsum', value: 'Soritos-Avamsum' },
    { label: 'Soros-Axaesum', value: 'Soros-Axaesum' },
    { label: 'Soues-Uzurtum', value: 'Soues-Uzurtum' },
    { label: 'Souitos-Oiozlum', value: 'Souitos-Oiozlum' },
    { label: 'Souos-Availos', value: 'Souos-Availos' },
    { label: 'Souos-Ososlos', value: 'Souos-Ososlos' },
    { label: 'Souos-Umogaum', value: 'Souos-Umogaum' },
    { label: 'Suyites-Avuotum', value: 'Suyites-Avuotum' },
    { label: 'Suyites-Uzurtum', value: 'Suyites-Uzurtum' },
    { label: 'Suyitos-Axaesum', value: 'Suyitos-Axaesum' },
    { label: 'Suyitos-Ofugtum', value: 'Suyitos-Ofugtum' },
    { label: 'Suyitos-Oyarlos', value: 'Suyitos-Oyarlos' },
    { label: 'Suyos-Onaytum', value: 'Suyos-Onaytum' },
    { label: 'Synites-Aoarsum', value: 'Synites-Aoarsum' },
    { label: 'Synitos-Availos', value: 'Synitos-Availos' },
    { label: 'Synitos-Ofurlos', value: 'Synitos-Ofurlos' },
    { label: 'Synitos-Ososlos', value: 'Synitos-Ososlos' },
    { label: 'Synos-Ayailos', value: 'Synos-Ayailos' },
    { label: 'Synos-Oyarlos', value: 'Synos-Oyarlos' },
    { label: 'Tasitos-Obayam', value: 'Tasitos-Obayam' },
    { label: 'Tasitos-Ulaurom', value: 'Tasitos-Ulaurom' },
    { label: 'Tasos-Iriglos', value: 'Tasos-Iriglos' },
    { label: 'Tebitos-Igaelum', value: 'Tebitos-Igaelum' },
    { label: 'Tebitos-Odoxlum', value: 'Tebitos-Odoxlum' },
    { label: 'Teros-Auiusum', value: 'Teros-Auiusum' },
    { label: 'Tetitos-Ayoslum', value: 'Tetitos-Ayoslum' },
    { label: 'Tetos-Igaelum', value: 'Tetos-Igaelum' },
    { label: 'Tetos-Ulaurom', value: 'Tetos-Ulaurom' },
    { label: 'Tieitos-Eyexrom', value: 'Tieitos-Eyexrom' },
    { label: 'Tieitos-Ouultum', value: 'Tieitos-Ouultum' },
    { label: 'Tieos-Ayoslum', value: 'Tieos-Ayoslum' },
    { label: 'Tilitos-Ataglos', value: 'Tilitos-Ataglos' },
    { label: 'Tiros-Odoxlum', value: 'Tiros-Odoxlum' },
    { label: 'Tiros-Ouultum', value: 'Tiros-Ouultum' },
    { label: 'Tonitos-Igurlum', value: 'Tonitos-Igurlum' },
    { label: 'Tonitos-Uxavrom', value: 'Tonitos-Uxavrom' },
    { label: 'Tonos-Aboysum', value: 'Tonos-Aboysum' },
    { label: 'Tonos-Obayam', value: 'Tonos-Obayam' },
    { label: 'Toritos-Iriglos', value: 'Toritos-Iriglos' },
    { label: 'Touos-Ataglos', value: 'Touos-Ataglos' },
    { label: 'Touos-Uoemtum', value: 'Touos-Uoemtum' },
    { label: 'Turitos-Atatlos', value: 'Turitos-Atatlos' },
    { label: 'Turitos-Uoemtum', value: 'Turitos-Uoemtum' },
    { label: 'Tuyitos-Aboysum', value: 'Tuyitos-Aboysum' },
    { label: 'Tuyitos-Auiusum', value: 'Tuyitos-Auiusum' },
    { label: 'Tynos-Atatlos', value: 'Tynos-Atatlos' },
    { label: 'Tynos-Eyexrom', value: 'Tynos-Eyexrom' },
    { label: 'Tynos-Igurlum', value: 'Tynos-Igurlum' },
    { label: 'Tynos-Uxavrom', value: 'Tynos-Uxavrom' },
    { label: 'Xases-Ataglos', value: 'Xases-Ataglos' },
    { label: 'Xases-Oxoulum', value: 'Xases-Oxoulum' },
    { label: 'Xasos-Aeoilos', value: 'Xasos-Aeoilos' },
    { label: 'Xasos-Aoemaum', value: 'Xasos-Aoemaum' },
    { label: 'Xasos-Oneulum', value: 'Xasos-Oneulum' },
    { label: 'Xebitos-Oyogam', value: 'Xebitos-Oyogam' },
    { label: 'Xebos-Emimsum', value: 'Xebos-Emimsum' },
    { label: 'Xebos-Exostum', value: 'Xebos-Exostum' },
    { label: 'Xerites-Oxoulum', value: 'Xerites-Oxoulum' },
    { label: 'Xetitos-Emimsum', value: 'Xetitos-Emimsum' },
    { label: 'Xetitos-Oneulum', value: 'Xetitos-Oneulum' },
    { label: 'Xetos-Obursum', value: 'Xetos-Obursum' },
    { label: 'Xiles-Aiavlum', value: 'Xiles-Aiavlum' },
    { label: 'Xilitos-Aoemaum', value: 'Xilitos-Aoemaum' },
    { label: 'Xilos-Osayam', value: 'Xilos-Osayam' },
    { label: 'Xiros-Aiairom', value: 'Xiros-Aiairom' },
    { label: 'Xonites-Aiavlum', value: 'Xonites-Aiavlum' },
    { label: 'Xoritos-Aiairom', value: 'Xoritos-Aiairom' },
    { label: 'Xoritos-Exostum', value: 'Xoritos-Exostum' },
    { label: 'Xoritos-Osayam', value: 'Xoritos-Osayam' },
    { label: 'Xouitos-Aeoilos', value: 'Xouitos-Aeoilos' },
    { label: 'Xouitos-Eyoztum', value: 'Xouitos-Eyoztum' },
    { label: 'Xouos-Aioblos', value: 'Xouos-Aioblos' },
    { label: 'Xurites-Ataglos', value: 'Xurites-Ataglos' },
    { label: 'Xuros-Eyoztum', value: 'Xuros-Eyoztum' },
    { label: 'Xuyitos-Aioblos', value: 'Xuyitos-Aioblos' },
    { label: 'Xynitos-Obursum', value: 'Xynitos-Obursum' },
    { label: 'Xynos-Oyogam', value: 'Xynos-Oyogam' }
];

export const Mapvalues = {
    red: redMapArray,
    blue: blueMapArray,
    roads: roadsMapArray,
    black: blackMapArray,
    yellow: yellowMapArray,
}

export const ZoneColor: ISelect[] = [
    { label: 'Red', value: 'red' },
    { label: 'Blue', value: 'blue' },
    { label: 'Roads', value: 'roads' },
    { label: 'Black', value: 'black' },
    { label: 'Yellow', value: 'yellow' },
]