import { ISelect } from "./types";

// ========== Blue ZONE ==========
const blueMapArray: ISelect[] = [
    { label: "Bellever Tor", value: "blue" },
    { label: "Birchcopse", value: "blue" },
    { label: "Blackthorn Quarry", value: "blue" },
    { label: "Brent Knoll", value: "blue" },
    { label: "Bryn Gorge", value: "blue" },
    { label: "Cedarcopse", value: "blue" },
    { label: "Chillhag", value: "blue" },
    { label: "Cracked Earth", value: "blue" },
    { label: "Crose Gorge", value: "blue" },
    { label: "Curlew Fen", value: "blue" },
    { label: "Dewleaf Fen", value: "blue" },
    { label: "Dryfield Meadow", value: "blue" },
    { label: "Drywater Meadow", value: "blue" },
    { label: "Dusklight Fen", value: "blue" },
    { label: "Ferndell", value: "blue" },
    { label: "Flynsdell", value: "blue" },
    { label: "Fog Fen", value: "blue" },
    { label: "Fractured Ground", value: "blue" },
    { label: "Goffers Knoll", value: "blue" },
    { label: "Gwan Gorge", value: "blue" },
    { label: "Haldon Tor", value: "blue" },
    { label: "Haytor", value: "blue" },
    { label: "Kilmar Tor", value: "blue" },
    { label: "Larchroad", value: "blue" },
    { label: "Longmarch Meadow", value: "blue" },
    { label: "Mase Knoll", value: "blue" },
    { label: "Mawar Gorge", value: "blue" },
    { label: "Murky Fen", value: "blue" },
    { label: "Oakcopse", value: "blue" },
    { label: "Pen Fenair", value: "blue" },
    { label: "Pen Garn", value: "blue" },
    { label: "Pen Gent", value: "blue" },
    { label: "Pen Kerrig", value: "blue" },
    { label: "Pen Uchaf", value: "blue" },
    { label: "Pinecopse", value: "blue" },
    { label: "Prospector's Hope", value: "blue" },
    { label: "Redlake", value: "blue" },
    { label: "Russerdell", value: "blue" },
    { label: "Saddle Tor", value: "blue" },
    { label: "Sandgust Cleft", value: "blue" },
    { label: "Slimehag", value: "blue" },
    { label: "Smoothfloor Cleft", value: "blue" },
    { label: "Stagbourne", value: "blue" },
    { label: "Steelhide Meadow", value: "blue" },
    { label: "Stinkhag", value: "blue" },
    { label: "VegAnimTest", value: "blue" },
    { label: "Vixen Tor", value: "blue" },
    { label: "Windripple Fen", value: "blue" }
];

// ========== Yellow ZONE ==========
const yellowMapArray: ISelect[] = [
    { label: "Adrens Hill", value: "yellow" },
    { label: "Aspenwood", value: "yellow" },
    { label: "Bonepool Marsh", value: "yellow" },
    { label: "Brons Hill", value: "yellow" },
    { label: "Cairn Camain", value: "yellow" },
    { label: "Cairn Cloch", value: "yellow" },
    { label: "Cairn Darg", value: "yellow" },
    { label: "Cairn Drain", value: "yellow" },
    { label: "Cairn Fidair", value: "yellow" },
    { label: "Cairn Glascore", value: "yellow" },
    { label: "Cairn Gorm", value: "yellow" },
    { label: "Carns Hill", value: "yellow" },
    { label: "Caulder Fissure", value: "yellow" },
    { label: "Croker Hill", value: "yellow" },
    { label: "Deeproot Wood", value: "yellow" },
    { label: "Drownhorse Basin", value: "yellow" },
    { label: "Eldon Hill", value: "yellow" },
    { label: "Falsestep Marsh", value: "yellow" },
    { label: "Felniks Hill", value: "yellow" },
    { label: "Flatriver Trough", value: "yellow" },
    { label: "Goldshimmer Plain", value: "yellow" },
    { label: "Gutras Hill", value: "yellow" },
    { label: "Hornbeam Wood", value: "yellow" },
    { label: "Inis Mon", value: "yellow" },
    { label: "Lazygrass Plain", value: "yellow" },
    { label: "Lewsdon Hill", value: "yellow" },
    { label: "Longshadow Plain", value: "yellow" },
    { label: "Nightcreak Marsh", value: "yellow" },
    { label: "Parchthroat Plain", value: "yellow" },
    { label: "Redstone Plain", value: "yellow" },
    { label: "Rowanwood", value: "yellow" },
    { label: "Sleetwater Basin", value: "yellow" },
    { label: "Slithertail Marsh", value: "yellow" },
    { label: "Slowtree Plain", value: "yellow" },
    { label: "Snapshaft Trough", value: "yellow" },
    { label: "Spindlewood", value: "yellow" },
    { label: "Tharcal Fissure", value: "yellow" },
    { label: "Wanderlure Basin", value: "yellow" },
    { label: "Willow Wood", value: "yellow" },
    { label: "Willowsigh Marsh", value: "yellow" },
    { label: "Wispwhisper Marsh", value: "yellow" },
    { label: "Yew Wood", value: "yellow" }
];

// ========== Red ZONE ==========
const redMapArray: ISelect[] = [
    { label: "Anklesnag Mire", value: "red" },
    { label: "Astolat", value: "red" },
    { label: "Birken Fell", value: "red" },
    { label: "Bowscale Fell", value: "red" },
    { label: "Broken Fell", value: "red" },
    { label: "Camlann", value: "red" },
    { label: "Creag Dhor", value: "red" },
    { label: "Creag Garr", value: "red" },
    { label: "Creag Meagir", value: "red" },
    { label: "Creag Morr", value: "red" },
    { label: "Darkground Swamp", value: "red" },
    { label: "Deadvein Gully", value: "red" },
    { label: "Domhain Chasm", value: "red" },
    { label: "Dusktree Swamp", value: "red" },
    { label: "Flimmerair Steppe", value: "red" },
    { label: "Garrow Fell", value: "red" },
    { label: "Highbole Glen", value: "red" },
    { label: "Kindlegrass Steppe", value: "red" },
    { label: "Longtimber Glen", value: "red" },
    { label: "Malag Crevasse", value: "red" },
    { label: "Mardale", value: "red" },
    { label: "Murkweald", value: "red" },
    { label: "Nightbloom Forest", value: "red" },
    { label: "Owlsong Glen", value: "red" },
    { label: "Roastcorpse Steppe", value: "red" },
    { label: "Runnel Sink", value: "red" },
    { label: "Shiftshadow Expanse", value: "red" },
    { label: "Spectral Sump", value: "red" },
    { label: "Stumprot Swamp", value: "red" },
    { label: "Wyre Forest", value: "red" }
];

// ========== Black ZONE ==========
const blackMapArray: ISelect[] = [
    { label: "Avalanche Incline", value: "black" },
    { label: "Avalanche Ravine", value: "black" },
    { label: "Battlebrae Flatland", value: "black" },
    { label: "Battlebrae Grassland", value: "black" },
    { label: "Battlebrae Lake", value: "black" },
    { label: "Battlebrae Meadow", value: "black" },
    { label: "Battlebrae Peaks", value: "black" },
    { label: "Battlebrae Plain", value: "black" },
    { label: "Black Monastery", value: "black" },
    { label: "Bleachskull Desert", value: "black" },
    { label: "Bleachskull Steppe", value: "black" },
    { label: "Braemore Lowland", value: "black" },
    { label: "Braemore Upland", value: "black" },
    { label: "Brambleshore Hinterlands", value: "black" },
    { label: "Citadel of Ash", value: "black" },
    { label: "Daemonium Keep", value: "black" },
    { label: "Darkbough Snag", value: "black" },
    { label: "Deadpine Forest", value: "black" },
    { label: "Deathreach Priory", value: "black" },
    { label: "Deathwisp Bog", value: "black" },
    { label: "Deathwisp Sink", value: "black" },
    { label: "Deepwood Copse", value: "black" },
    { label: "Deepwood Dell", value: "black" },
    { label: "Deepwood Gorge", value: "black" },
    { label: "Deepwood Pines", value: "black" },
    { label: "Driftwood Glen", value: "black" },
    { label: "Driftwood Hollow", value: "black" },
    { label: "Driftwood Vale", value: "black" },
    { label: "Drownfield Course", value: "black" },
    { label: "Drownfield Fen", value: "black" },
    { label: "Drownfield Mire", value: "black" },
    { label: "Drownfield Quag", value: "black" },
    { label: "Drownfield Rut", value: "black" },
    { label: "Drownfield Sink", value: "black" },
    { label: "Drownfield Slough", value: "black" },
    { label: "Drownfield Wetland", value: "black" },
    { label: "Drybasin Oasis", value: "black" },
    { label: "Drybasin Riverbed", value: "black" },
    { label: "Drytop Pillars", value: "black" },
    { label: "Drytop Riverbed", value: "black" },
    { label: "Dryvein Confluence", value: "black" },
    { label: "Dryvein Cross", value: "black" },
    { label: "Dryvein End", value: "black" },
    { label: "Dryvein Oasis", value: "black" },
    { label: "Dryvein Plain", value: "black" },
    { label: "Dryvein Riverbed", value: "black" },
    { label: "Dryvein Steppe", value: "black" },
    { label: "Eldersleep", value: "black" },
    { label: "Everwinter Crossing", value: "black" },
    { label: "Everwinter Expanse", value: "black" },
    { label: "Everwinter Gap", value: "black" },
    { label: "Everwinter Gorge", value: "black" },
    { label: "Everwinter Incline", value: "black" },
    { label: "Everwinter Passage", value: "black" },
    { label: "Everwinter Peak", value: "black" },
    { label: "Everwinter Plain", value: "black" },
    { label: "Everwinter Reach", value: "black" },
    { label: "Everwinter Shores", value: "black" },
    { label: "Eye of the Forest", value: "black" },
    { label: "Farshore Bay", value: "black" },
    { label: "Farshore Cape", value: "black" },
    { label: "Farshore Drylands", value: "black" },
    { label: "Farshore Esker", value: "black" },
    { label: "Farshore Heath", value: "black" },
    { label: "Farshore Lagoon", value: "black" },
    { label: "Firesink Caldera", value: "black" },
    { label: "Firesink Trench", value: "black" },
    { label: "Flammog Desolation", value: "black" },
    { label: "Flammog Fork", value: "black" },
    { label: "Flammog Valley", value: "black" },
    { label: "Flatrock Cliffs", value: "black" },
    { label: "Flatrock Plateau", value: "black" },
    { label: "Floatshoal Bight", value: "black" },
    { label: "Floatshoal Fissure", value: "black" },
    { label: "Floatshoal Floe", value: "black" },
    { label: "Frostbite Chasm", value: "black" },
    { label: "Frostbite Mountain", value: "black" },
    { label: "Frostpeak Ascent", value: "black" },
    { label: "Frostpeak Vista", value: "black" },
    { label: "Frostseep Crevasse", value: "black" },
    { label: "Frostseep Ravine", value: "black" },
    { label: "Frostspring Passage", value: "black" },
    { label: "Frostspring Volcano", value: "black" },
    { label: "Giantweald Copse", value: "black" },
    { label: "Giantweald Dale", value: "black" },
    { label: "Giantweald Edge", value: "black" },
    { label: "Giantweald Glade", value: "black" },
    { label: "Giantweald Roots", value: "black" },
    { label: "Giantweald Woods", value: "black" },
    { label: "Glacierbreak Summit", value: "black" },
    { label: "Glacierfall Canyon", value: "black" },
    { label: "Glacierfall Cross", value: "black" },
    { label: "Glacierfall Fissure", value: "black" },
    { label: "Glacierfall Pass", value: "black" },
    { label: "Glacierfall Passage", value: "black" },
    { label: "Glacierfall Valley", value: "black" },
    { label: "Gravemound Brim", value: "black" },
    { label: "Gravemound Cliffs", value: "black" },
    { label: "Gravemound Hills", value: "black" },
    { label: "Gravemound Knoll", value: "black" },
    { label: "Gravemound Slope", value: "black" },
    { label: "Greenhollow Copse", value: "black" },
    { label: "Greenhollow Vale", value: "black" },
    { label: "Greenshore Bay", value: "black" },
    { label: "Greenshore Peninsula", value: "black" },
    { label: "Highstone Grassland", value: "black" },
    { label: "Highstone Loch", value: "black" },
    { label: "Highstone Meadow", value: "black" },
    { label: "Highstone Mound", value: "black" },
    { label: "Highstone Plains", value: "black" },
    { label: "Highstone Plateau", value: "black" },
    { label: "Hightree Borderlands", value: "black" },
    { label: "Hightree Cliffs", value: "black" },
    { label: "Hightree Dale", value: "black" },
    { label: "Hightree Enclave", value: "black" },
    { label: "Hightree Glade", value: "black" },
    { label: "Hightree Hillock", value: "black" },
    { label: "Hightree Isle", value: "black" },
    { label: "Hightree Lake", value: "black" },
    { label: "Hightree Levee", value: "black" },
    { label: "Hightree Pass", value: "black" },
    { label: "Hightree Steep", value: "black" },
    { label: "Hightree Strand", value: "black" },
    { label: "Iceburn Cliffs", value: "black" },
    { label: "Iceburn Firth", value: "black" },
    { label: "Iceburn Peaks", value: "black" },
    { label: "Iceburn Tundra", value: "black" },
    { label: "Longfen Arms", value: "black" },
    { label: "Longfen Marsh", value: "black" },
    { label: "Longfen Veins", value: "black" },
    { label: "Meltwater Bog", value: "black" },
    { label: "Meltwater Channel", value: "black" },
    { label: "Meltwater Delta", value: "black" },
    { label: "Meltwater Sump", value: "black" },
    { label: "Mudfoot Mounds", value: "black" },
    { label: "Mudfoot Sump", value: "black" },
    { label: "Munten Fell", value: "black" },
    { label: "Munten Rise", value: "black" },
    { label: "Munten Tundra", value: "black" },
    { label: "Murdergulch Cross", value: "black" },
    { label: "Murdergulch Divide", value: "black" },
    { label: "Murdergulch Gap", value: "black" },
    { label: "Murdergulch Ravine", value: "black" },
    { label: "Murdergulch Trail", value: "black" },
    { label: "Northstrand Beach", value: "black" },
    { label: "Northstrand Dunes", value: "black" },
    { label: "Parchsand Cliffs", value: "black" },
    { label: "Parchsand Drought", value: "black" },
    { label: "Razorrock Bank", value: "black" },
    { label: "Razorrock Chasm", value: "black" },
    { label: "Razorrock Edge", value: "black" },
    { label: "Razorrock Gulch", value: "black" },
    { label: "Razorrock Passage", value: "black" },
    { label: "Razorrock Ravine", value: "black" },
    { label: "Razorrock Valley", value: "black" },
    { label: "Razorrock Verge", value: "black" },
    { label: "Redtree Enclave", value: "black" },
    { label: "Rivercopse Crossing", value: "black" },
    { label: "Rivercopse Curve", value: "black" },
    { label: "Rivercopse Fount", value: "black" },
    { label: "Rivercopse Path", value: "black" },
    { label: "Runnelvein Bog", value: "black" },
    { label: "Runnelvein Sink", value: "black" },
    { label: "Runnelvein Slough", value: "black" },
    { label: "Sandmount Ascent", value: "black" },
    { label: "Sandmount Desert", value: "black" },
    { label: "Sandmount Esker", value: "black" },
    { label: "Sandmount Strand", value: "black" },
    { label: "Sandrift Coast", value: "black" },
    { label: "Sandrift Dunes", value: "black" },
    { label: "Sandrift Expanse", value: "black" },
    { label: "Sandrift Fringe", value: "black" },
    { label: "Sandrift Prairie", value: "black" },
    { label: "Sandrift Shore", value: "black" },
    { label: "Sandrift Steppe", value: "black" },
    { label: "Scuttlesink Marsh", value: "black" },
    { label: "Scuttlesink Mouth", value: "black" },
    { label: "Scuttlesink Pools", value: "black" },
    { label: "Shaleheath Hills", value: "black" },
    { label: "Shaleheath Steep", value: "black" },
    { label: "Skullmarsh Lower", value: "black" },
    { label: "Skullmarsh Upper", value: "black" },
    { label: "Skylake Bridge", value: "black" },
    { label: "Skylake Hinterlands", value: "black" },
    { label: "Skysand Plateau", value: "black" },
    { label: "Skysand Ridge", value: "black" },
    { label: "Slakesands Canyon", value: "black" },
    { label: "Slakesands Mesa", value: "black" },
    { label: "Southgrove Copse", value: "black" },
    { label: "Southgrove Escarp", value: "black" },
    { label: "Southgrove Thicket", value: "black" },
    { label: "Springsump Basin", value: "black" },
    { label: "Springsump Melt", value: "black" },
    { label: "Springsump Wetland", value: "black" },
    { label: "Stonelake Fields", value: "black" },
    { label: "Stonelake Hillock", value: "black" },
    { label: "Stonemouth Bay", value: "black" },
    { label: "Stonemouth Northbluff", value: "black" },
    { label: "Stonemouth Southbluff", value: "black" },
    { label: "Sunfang Approach", value: "black" },
    { label: "Sunfang Cliffs", value: "black" },
    { label: "Sunfang Dawn", value: "black" },
    { label: "Sunfang Ravine", value: "black" },
    { label: "Sunfang Wasteland", value: "black" },
    { label: "Sunkenbough Spring", value: "black" },
    { label: "Sunkenbough Woods", value: "black" },
    { label: "Sunstrand Delta", value: "black" },
    { label: "Sunstrand Dunes", value: "black" },
    { label: "Sunstrand Quicksands", value: "black" },
    { label: "Sunstrand Shoal", value: "black" },
    { label: "Swiftsands Basin", value: "black" },
    { label: "Swiftsands Chaparral", value: "black" },
    { label: "Swiftsands Plain", value: "black" },
    { label: "Thirstwater Gully", value: "black" },
    { label: "Thirstwater Steppe", value: "black" },
    { label: "Thirstwater Waste", value: "black" },
    { label: "Thunderrock Ascent", value: "black" },
    { label: "Thunderrock Draw", value: "black" },
    { label: "Thunderrock Rapids", value: "black" },
    { label: "Thunderrock Upland", value: "black" },
    { label: "Timberscar Copse", value: "black" },
    { label: "Timberscar Dell", value: "black" },
    { label: "Timberslope Bridge", value: "black" },
    { label: "Timberslope Dell", value: "black" },
    { label: "Timberslope Grove", value: "black" },
    { label: "Timbertop Dale", value: "black" },
    { label: "Timbertop Escarp", value: "black" },
    { label: "Timbertop Wood", value: "black" },
    { label: "Twinchannel Narrows", value: "black" },
    { label: "Unhallowed Cloister", value: "black" },
    { label: "Wailing Bulwark", value: "black" },
    { label: "Watchwood Bluffs", value: "black" },
    { label: "Watchwood Grove", value: "black" },
    { label: "Watchwood Lakeside", value: "black" },
    { label: "Watchwood Precipice", value: "black" },
    { label: "Westweald Shore", value: "black" },
    { label: "Westweald Thicket", value: "black" },
    { label: "Wetgrave Bog", value: "black" },
    { label: "Wetgrave Marsh", value: "black" },
    { label: "Wetgrave Swale", value: "black" },
    { label: "Whitebank Cross", value: "black" },
    { label: "Whitebank Descent", value: "black" },
    { label: "Whitebank Ridge", value: "black" },
    { label: "Whitebank Shore", value: "black" },
    { label: "Whitebank Stream", value: "black" },
    { label: "Whitebank Wall", value: "black" },
    { label: "Whitecliff Expanse", value: "black" },
    { label: "Whitecliff Peak", value: "black" },
    { label: "Whitepeak Ascent", value: "black" },
    { label: "Whitepeak Spring", value: "black" },
    { label: "Whitepeak Tundra", value: "black" },
    { label: "Whitewall Pass", value: "black" },
    { label: "Whitewall Ridge", value: "black" },
    { label: "Widemoor Delta", value: "black" },
    { label: "Widemoor End", value: "black" },
    { label: "Widemoor Estuary", value: "black" },
    { label: "Widemoor Fen", value: "black" },
    { label: "Widemoor Flats", value: "black" },
    { label: "Widemoor Hills", value: "black" },
    { label: "Widemoor Pool", value: "black" },
    { label: "Widemoor Shore", value: "black" },
    { label: "Widemoor Woods", value: "black" },
    { label: "Willowshade Hills", value: "black" },
    { label: "Willowshade Icemarsh", value: "black" },
    { label: "Willowshade Lake", value: "black" },
    { label: "Willowshade Mire", value: "black" },
    { label: "Willowshade Pools", value: "black" },
    { label: "Willowshade Sink", value: "black" },
    { label: "Willowshade Wetlands", value: "black" },
    { label: "Windgrass Border", value: "black" },
    { label: "Windgrass Coast", value: "black" },
    { label: "Windgrass Fields", value: "black" },
    { label: "Windgrass Gully", value: "black" },
    { label: "Windgrass Precipice", value: "black" },
    { label: "Windgrass Rill", value: "black" },
    { label: "Windgrass Terrace", value: "black" }
];

// ========== Roads ZONE ==========
const roadsMapArray: ISelect[] = [
    { label: "Cases-Ugumlos", value: "roads" },
    { label: "Casitos-Alieam", value: "roads" },
    { label: "Casitos-Atinaum", value: "roads" },
    { label: "Casitos-Avaelum", value: "roads" },
    { label: "Casos-Aiagsum", value: "roads" },
    { label: "Casos-Aximam", value: "roads" },
    { label: "Casos-Ayosrom", value: "roads" },
    { label: "Casos-Uruxtum", value: "roads" },
    { label: "Cebitos-Aeaylum", value: "roads" },
    { label: "Cebos-Avemlum", value: "roads" },
    { label: "Ceres-Iooinum", value: "roads" },
    { label: "Ceritos-Avulsum", value: "roads" },
    { label: "Ceros-Aeaylum", value: "roads" },
    { label: "Cetitos-Aiayrom", value: "roads" },
    { label: "Cetitos-Avixnum", value: "roads" },
    { label: "Cetitos-Aximam", value: "roads" },
    { label: "Cetos-Obaelos", value: "roads" },
    { label: "Cieites-Ugumlos", value: "roads" },
    { label: "Cieitos-Avioaum", value: "roads" },
    { label: "Cieitos-Ayosrom", value: "roads" },
    { label: "Cieitos-Obaelos", value: "roads" },
    { label: "Cieitos-Otatrom", value: "roads" },
    { label: "Cieos-Atatlum", value: "roads" },
    { label: "Cilitos-Opodam", value: "roads" },
    { label: "Cilos-Avioaum", value: "roads" },
    { label: "Cilos-Ofailos", value: "roads" },
    { label: "Cilos-Otatrom", value: "roads" },
    { label: "Conitos-Ofailos", value: "roads" },
    { label: "Conitos-Oxaeaum", value: "roads" },
    { label: "Conitos-Uruxtum", value: "roads" },
    { label: "Conos-Avaelum", value: "roads" },
    { label: "Coritos-Avemlum", value: "roads" },
    { label: "Coros-Aiayrom", value: "roads" },
    { label: "Coros-Alieam", value: "roads" },
    { label: "Coros-Atinaum", value: "roads" },
    { label: "Coues-Exakrom", value: "roads" },
    { label: "Couos-Ayayaum", value: "roads" },
    { label: "Couos-Opodam", value: "roads" },
    { label: "Curites-Exakrom", value: "roads" },
    { label: "Curitos-Ayayaum", value: "roads" },
    { label: "Curos-Avulsum", value: "roads" },
    { label: "Cuyites-Iooinum", value: "roads" },
    { label: "Cynitos-Aiagsum", value: "roads" },
    { label: "Cynitos-Atatlum", value: "roads" },
    { label: "Cynos-Avixnum", value: "roads" },
    { label: "Cynos-Oxaeaum", value: "roads" },
    { label: "Fasites-Azazsum", value: "roads" },
    { label: "Fasitos-Atezsum", value: "roads" },
    { label: "Fasitos-Oleraum", value: "roads" },
    { label: "Fasitos-Oyuctum", value: "roads" },
    { label: "Fasos-Ayiotum", value: "roads" },
    { label: "Febites-Opavun", value: "roads" },
    { label: "Febos-Acalun", value: "roads" },
    { label: "Ferites-Ohohtum", value: "roads" },
    { label: "Feritos-Enomaum", value: "roads" },
    { label: "Feritos-Osinsum", value: "roads" },
    { label: "Feros-Oyuctum", value: "roads" },
    { label: "Fetos-Aiaylos", value: "roads" },
    { label: "Fiees-Ohohtum", value: "roads" },
    { label: "Fieites-Unavtum", value: "roads" },
    { label: "Fieos-Aiuttum", value: "roads" },
    { label: "Fieos-Atezsum", value: "roads" },
    { label: "Files-Azazsum", value: "roads" },
    { label: "Filites-Izohun", value: "roads" },
    { label: "Filitos-Uzazlum", value: "roads" },
    { label: "Filos-Abalam", value: "roads" },
    { label: "Firitos-Alodrom", value: "roads" },
    { label: "Firos-Aiavam", value: "roads" },
    { label: "Firos-Enomaum", value: "roads" },
    { label: "Firos-Ezatam", value: "roads" },
    { label: "Firos-Osinsum", value: "roads" },
    { label: "Fones-Opavun", value: "roads" },
    { label: "Fonitos-Amaurom", value: "roads" },
    { label: "Fonos-Aiugsum", value: "roads" },
    { label: "Fonos-Oleraum", value: "roads" },
    { label: "Foritos-Aiaylos", value: "roads" },
    { label: "Foros-Egoisum", value: "roads" },
    { label: "Foros-Uzazlum", value: "roads" },
    { label: "Foues-Aeaosum", value: "roads" },
    { label: "Fouitos-Aiuttum", value: "roads" },
    { label: "Fouos-Agosaum", value: "roads" },
    { label: "Fouos-Amaurom", value: "roads" },
    { label: "Furitos-Aiavam", value: "roads" },
    { label: "Fuyes-Izohun", value: "roads" },
    { label: "Fuyitos-Acalun", value: "roads" },
    { label: "Fuyitos-Ayiotum", value: "roads" },
    { label: "Fynes-Unavtum", value: "roads" },
    { label: "Fynites-Aeaosum", value: "roads" },
    { label: "Fynitos-Abalam", value: "roads" },
    { label: "Fynitos-Agosaum", value: "roads" },
    { label: "Fynitos-Aiugsum", value: "roads" },
    { label: "Fynitos-Egoisum", value: "roads" },
    { label: "Fynitos-Ezatam", value: "roads" },
    { label: "Fynos-Alodrom", value: "roads" },
    { label: "Hasitos-Avaolum", value: "roads" },
    { label: "Hasitos-Umayaum", value: "roads" },
    { label: "Hasos-Agoitum", value: "roads" },
    { label: "Hasos-Ayousum", value: "roads" },
    { label: "Hasos-Inayaum", value: "roads" },
    { label: "Hasos-Iuimaum", value: "roads" },
    { label: "Hasos-Osuorom", value: "roads" },
    { label: "Hebes-Ouaylos", value: "roads" },
    { label: "Hebites-Exemrom", value: "roads" },
    { label: "Hebitos-Atontum", value: "roads" },
    { label: "Hebos-Ulamsum", value: "roads" },
    { label: "Heritos-Exozlos", value: "roads" },
    { label: "Heritos-Eyoztum", value: "roads" },
    { label: "Heritos-Inayaum", value: "roads" },
    { label: "Heros-Atoyam", value: "roads" },
    { label: "Hetitos-Iuaerom", value: "roads" },
    { label: "Hieos-Aiigaum", value: "roads" },
    { label: "Hieos-Avaolum", value: "roads" },
    { label: "Hiles-Izizaum", value: "roads" },
    { label: "Hilites-Ugumtum", value: "roads" },
    { label: "Hilitos-Aiigaum", value: "roads" },
    { label: "Hilitos-Osuorom", value: "roads" },
    { label: "Hiros-Exozlos", value: "roads" },
    { label: "Hiros-Iuaerom", value: "roads" },
    { label: "Honites-Izizaum", value: "roads" },
    { label: "Honitos-Uxeulum", value: "roads" },
    { label: "Honos-Oyezam", value: "roads" },
    { label: "Honos-Umayaum", value: "roads" },
    { label: "Horos-Ohenlum", value: "roads" },
    { label: "Hures-Ugumtum", value: "roads" },
    { label: "Hurites-Ieatun", value: "roads" },
    { label: "Hurites-Ouaylos", value: "roads" },
    { label: "Huritos-Iuimaum", value: "roads" },
    { label: "Huritos-Oiaelos", value: "roads" },
    { label: "Huros-Atontum", value: "roads" },
    { label: "Huyes-Ogozlum", value: "roads" },
    { label: "Huyitos-Agoitum", value: "roads" },
    { label: "Huyitos-Ohenlum", value: "roads" },
    { label: "Huyos-Eyoztum", value: "roads" },
    { label: "Huyos-Uxeulum", value: "roads" },
    { label: "Hynes-Exemrom", value: "roads" },
    { label: "Hynes-Ieatun", value: "roads" },
    { label: "Hynites-Ogozlum", value: "roads" },
    { label: "Hynitos-Atoyam", value: "roads" },
    { label: "Hynitos-Ayousum", value: "roads" },
    { label: "Hynitos-Oyezam", value: "roads" },
    { label: "Hynitos-Ulamsum", value: "roads" },
    { label: "Hynos-Oiaelos", value: "roads" },
    { label: "Oasitos-Aoeuam", value: "roads" },
    { label: "Oasos-Eraerom", value: "roads" },
    { label: "Oasos-Uromlum", value: "roads" },
    { label: "Oebitos-Eraerom", value: "roads" },
    { label: "Oebitos-Oyozam", value: "roads" },
    { label: "Oebos-Ixakaum", value: "roads" },
    { label: "Oeritos-Ecunsum", value: "roads" },
    { label: "Oeritos-Oyexlos", value: "roads" },
    { label: "Oetos-Ofailos", value: "roads" },
    { label: "Oetos-Oyexlos", value: "roads" },
    { label: "Oieitos-Ixakaum", value: "roads" },
    { label: "Oieos-Umiutum", value: "roads" },
    { label: "Oires-Oloblum", value: "roads" },
    { label: "Oiritos-Eramtum", value: "roads" },
    { label: "Oiros-Alaiam", value: "roads" },
    { label: "Oonitos-Umiutum", value: "roads" },
    { label: "Ooros-Ataltum", value: "roads" },
    { label: "Ooros-Ecunsum", value: "roads" },
    { label: "Oouitos-Alaiam", value: "roads" },
    { label: "Oures-Araosum", value: "roads" },
    { label: "Ouritos-Ataltum", value: "roads" },
    { label: "Ouritos-Ofailos", value: "roads" },
    { label: "Ouyos-Aoeuam", value: "roads" },
    { label: "Oynites-Araosum", value: "roads" },
    { label: "Oynites-Oloblum", value: "roads" },
    { label: "Oynitos-Uromlum", value: "roads" },
    { label: "Oynos-Eramtum", value: "roads" },
    { label: "Oynos-Oyozam", value: "roads" },
    { label: "Pasos-Avosam", value: "roads" },
    { label: "Pebos-Avosrom", value: "roads" },
    { label: "Peritos-Avosam", value: "roads" },
    { label: "Peritos-Oconun", value: "roads" },
    { label: "Peros-Aiataum", value: "roads" },
    { label: "Petitos-Amayam", value: "roads" },
    { label: "Petitos-Avosrom", value: "roads" },
    { label: "Petos-Aietam", value: "roads" },
    { label: "Pieos-Eterrom", value: "roads" },
    { label: "Pieos-Ofairom", value: "roads" },
    { label: "Pilitos-Eterrom", value: "roads" },
    { label: "Pirites-Unatam", value: "roads" },
    { label: "Piritos-Ofavam", value: "roads" },
    { label: "Piritos-Opabrom", value: "roads" },
    { label: "Ponitos-Aiayrom", value: "roads" },
    { label: "Poros-Aiayrom", value: "roads" },
    { label: "Poros-Oconun", value: "roads" },
    { label: "Poues-Unatam", value: "roads" },
    { label: "Pouitos-Ofairom", value: "roads" },
    { label: "Pures-Ouozlum", value: "roads" },
    { label: "Puros-Amayam", value: "roads" },
    { label: "Puros-Ofavam", value: "roads" },
    { label: "Puyitos-Aiataum", value: "roads" },
    { label: "Pynites-Ouozlum", value: "roads" },
    { label: "Pynitos-Aietam", value: "roads" },
    { label: "Pynos-Opabrom", value: "roads" },
    { label: "Qiient-Al-Nusom", value: "roads" },
    { label: "Qiient-Al-Odesum", value: "roads" },
    { label: "Qiient-Al-Qinsis", value: "roads" },
    { label: "Qiient-Al-Tersas", value: "roads" },
    { label: "Qiient-Al-Viesis", value: "roads" },
    { label: "Qiient-Al-Vynsis", value: "roads" },
    { label: "Qiient-Et-Nusas", value: "roads" },
    { label: "Qiient-Et-Odetis", value: "roads" },
    { label: "Qiient-Et-Qinsum", value: "roads" },
    { label: "Qiient-Et-Tertum", value: "roads" },
    { label: "Qiient-In-Nutis", value: "roads" },
    { label: "Qiient-In-Odetum", value: "roads" },
    { label: "Qiient-In-Qinsis", value: "roads" },
    { label: "Qiient-In-Tersom", value: "roads" },
    { label: "Qiient-In-Viesis", value: "roads" },
    { label: "Qiient-In-Vyntum", value: "roads" },
    { label: "Qiient-Nutis", value: "roads" },
    { label: "Qiient-Oc-Odetum", value: "roads" },
    { label: "Qiient-Odesas", value: "roads" },
    { label: "Qiient-Qi-Nusom", value: "roads" },
    { label: "Qiient-Qi-Odesas", value: "roads" },
    { label: "Qiient-Qi-Tersas", value: "roads" },
    { label: "Qiient-Qi-Vynsis", value: "roads" },
    { label: "Qiient-Qinsum", value: "roads" },
    { label: "Qiient-Sa-Odetis", value: "roads" },
    { label: "Qiient-Si-Nusas", value: "roads" },
    { label: "Qiient-Si-Odesum", value: "roads" },
    { label: "Qiient-Si-Tertum", value: "roads" },
    { label: "Qiient-Tersom", value: "roads" },
    { label: "Qiient-Vyntum", value: "roads" },
    { label: "Qiitun-Al-Duosum", value: "roads" },
    { label: "Qiitun-Duosum", value: "roads" },
    { label: "Qiitun-Et-Vietis", value: "roads" },
    { label: "Qiitun-Et-Vynsom", value: "roads" },
    { label: "Qiitun-Si-Vynsom", value: "roads" },
    { label: "Qiitun-Vietis", value: "roads" },
    { label: "Quaent-Al-Nusis", value: "roads" },
    { label: "Quaent-Al-Odesum", value: "roads" },
    { label: "Quaent-Al-Qintis", value: "roads" },
    { label: "Quaent-Al-Tersis", value: "roads" },
    { label: "Quaent-Al-Viesom", value: "roads" },
    { label: "Quaent-Al-Vynsum", value: "roads" },
    { label: "Quaent-In-Nusis", value: "roads" },
    { label: "Quaent-In-Odesum", value: "roads" },
    { label: "Quaent-Qintis", value: "roads" },
    { label: "Quaent-Tersis", value: "roads" },
    { label: "Quaent-Viesom", value: "roads" },
    { label: "Quaent-Vynsum", value: "roads" },
    { label: "Quatun-Et-Nusas", value: "roads" },
    { label: "Quatun-Et-Odetum", value: "roads" },
    { label: "Quatun-Nusas", value: "roads" },
    { label: "Quatun-Odetum", value: "roads" },
    { label: "Sases-Aoarsum", value: "roads" },
    { label: "Sases-Avuotum", value: "roads" },
    { label: "Sasitos-Oyarlum", value: "roads" },
    { label: "Sasitos-Ugersum", value: "roads" },
    { label: "Sasitos-Umogaum", value: "roads" },
    { label: "Sasos-Abizaum", value: "roads" },
    { label: "Sasos-Egeylos", value: "roads" },
    { label: "Sasos-Oiozlum", value: "roads" },
    { label: "Sebos-Avoirom", value: "roads" },
    { label: "Sebos-Oyohun", value: "roads" },
    { label: "Sebos-Ugersum", value: "roads" },
    { label: "Secent-Al-Duosom", value: "roads" },
    { label: "Secent-Al-Nutum", value: "roads" },
    { label: "Secent-Al-Odetis", value: "roads" },
    { label: "Secent-Al-Qinsom", value: "roads" },
    { label: "Secent-Al-Tersum", value: "roads" },
    { label: "Secent-Al-Viesum", value: "roads" },
    { label: "Secent-Duosom", value: "roads" },
    { label: "Secent-Et-Odesis", value: "roads" },
    { label: "Secent-Et-Qinsas", value: "roads" },
    { label: "Secent-Et-Vyntum", value: "roads" },
    { label: "Secent-In-Tersum", value: "roads" },
    { label: "Secent-Nutum", value: "roads" },
    { label: "Secent-Odesom", value: "roads" },
    { label: "Secent-Qi-Odesom", value: "roads" },
    { label: "Secent-Qi-Qinsom", value: "roads" },
    { label: "Secent-Sa-Odesis", value: "roads" },
    { label: "Secent-Si-Odetis", value: "roads" },
    { label: "Secent-Si-Qinsas", value: "roads" },
    { label: "Secent-Viesum", value: "roads" },
    { label: "Secent-Vyntum", value: "roads" },
    { label: "Sectun-Al-Vyntis", value: "roads" },
    { label: "Sectun-Et-Tersas", value: "roads" },
    { label: "Sectun-In-Odesis", value: "roads" },
    { label: "Sectun-In-Qinsom", value: "roads" },
    { label: "Sectun-In-Vyntis", value: "roads" },
    { label: "Sectun-Oc-Odesis", value: "roads" },
    { label: "Sectun-Qinsom", value: "roads" },
    { label: "Sectun-Tersas", value: "roads" },
    { label: "Seritos-Egeylos", value: "roads" },
    { label: "Seritos-Onaytum", value: "roads" },
    { label: "Setent-Al-Duosas", value: "roads" },
    { label: "Setent-Al-Qinsum", value: "roads" },
    { label: "Setent-Al-Vietis", value: "roads" },
    { label: "Setent-Duosas", value: "roads" },
    { label: "Setent-Et-Nusum", value: "roads" },
    { label: "Setent-Et-Qintis", value: "roads" },
    { label: "Setent-In-Qinsum", value: "roads" },
    { label: "Setent-Nusum", value: "roads" },
    { label: "Setent-Qintis", value: "roads" },
    { label: "Setent-Vietis", value: "roads" },
    { label: "Setitos-Obobrom", value: "roads" },
    { label: "Setos-Aiaitum", value: "roads" },
    { label: "Setos-Avamsum", value: "roads" },
    { label: "Settun-Al-Nusis", value: "roads" },
    { label: "Settun-Al-Odetum", value: "roads" },
    { label: "Settun-Al-Tersom", value: "roads" },
    { label: "Settun-Al-Vynsis", value: "roads" },
    { label: "Settun-Et-Odetum", value: "roads" },
    { label: "Settun-In-Nusis", value: "roads" },
    { label: "Settun-In-Odetum", value: "roads" },
    { label: "Settun-Odetum", value: "roads" },
    { label: "Settun-Tersom", value: "roads" },
    { label: "Settun-Vynsis", value: "roads" },
    { label: "Sieos-Ofugtum", value: "roads" },
    { label: "Silitos-Abizaum", value: "roads" },
    { label: "Silos-Apenlum", value: "roads" },
    { label: "Silos-Oyarlum", value: "roads" },
    { label: "Siritos-Avoirom", value: "roads" },
    { label: "Siritos-Oyohun", value: "roads" },
    { label: "Siros-Obobrom", value: "roads" },
    { label: "Siros-Ofurlos", value: "roads" },
    { label: "Sonitos-Ayailos", value: "roads" },
    { label: "Soritos-Aiaitum", value: "roads" },
    { label: "Soritos-Apenlum", value: "roads" },
    { label: "Soritos-Avamsum", value: "roads" },
    { label: "Soros-Axaesum", value: "roads" },
    { label: "Soues-Uzurtum", value: "roads" },
    { label: "Souitos-Oiozlum", value: "roads" },
    { label: "Souos-Availos", value: "roads" },
    { label: "Souos-Ososlos", value: "roads" },
    { label: "Souos-Umogaum", value: "roads" },
    { label: "Suyites-Avuotum", value: "roads" },
    { label: "Suyites-Uzurtum", value: "roads" },
    { label: "Suyitos-Axaesum", value: "roads" },
    { label: "Suyitos-Ofugtum", value: "roads" },
    { label: "Suyitos-Oyarlos", value: "roads" },
    { label: "Suyos-Onaytum", value: "roads" },
    { label: "Synites-Aoarsum", value: "roads" },
    { label: "Synitos-Availos", value: "roads" },
    { label: "Synitos-Ofurlos", value: "roads" },
    { label: "Synitos-Ososlos", value: "roads" },
    { label: "Synos-Ayailos", value: "roads" },
    { label: "Synos-Oyarlos", value: "roads" },
    { label: "Tasitos-Obayam", value: "roads" },
    { label: "Tasitos-Ulaurom", value: "roads" },
    { label: "Tasos-Iriglos", value: "roads" },
    { label: "Tebitos-Igaelum", value: "roads" },
    { label: "Tebitos-Odoxlum", value: "roads" },
    { label: "Teros-Auiusum", value: "roads" },
    { label: "Tetitos-Ayoslum", value: "roads" },
    { label: "Tetos-Igaelum", value: "roads" },
    { label: "Tetos-Ulaurom", value: "roads" },
    { label: "Tieitos-Eyexrom", value: "roads" },
    { label: "Tieitos-Ouultum", value: "roads" },
    { label: "Tieos-Ayoslum", value: "roads" },
    { label: "Tilitos-Ataglos", value: "roads" },
    { label: "Tiros-Odoxlum", value: "roads" },
    { label: "Tiros-Ouultum", value: "roads" },
    { label: "Tonitos-Igurlum", value: "roads" },
    { label: "Tonitos-Uxavrom", value: "roads" },
    { label: "Tonos-Aboysum", value: "roads" },
    { label: "Tonos-Obayam", value: "roads" },
    { label: "Toritos-Iriglos", value: "roads" },
    { label: "Touos-Ataglos", value: "roads" },
    { label: "Touos-Uoemtum", value: "roads" },
    { label: "Turitos-Atatlos", value: "roads" },
    { label: "Turitos-Uoemtum", value: "roads" },
    { label: "Tuyitos-Aboysum", value: "roads" },
    { label: "Tuyitos-Auiusum", value: "roads" },
    { label: "Tynos-Atatlos", value: "roads" },
    { label: "Tynos-Eyexrom", value: "roads" },
    { label: "Tynos-Igurlum", value: "roads" },
    { label: "Tynos-Uxavrom", value: "roads" },
    { label: "Xases-Ataglos", value: "roads" },
    { label: "Xases-Oxoulum", value: "roads" },
    { label: "Xasos-Aeoilos", value: "roads" },
    { label: "Xasos-Aoemaum", value: "roads" },
    { label: "Xasos-Oneulum", value: "roads" },
    { label: "Xebitos-Oyogam", value: "roads" },
    { label: "Xebos-Emimsum", value: "roads" },
    { label: "Xebos-Exostum", value: "roads" },
    { label: "Xerites-Oxoulum", value: "roads" },
    { label: "Xetitos-Emimsum", value: "roads" },
    { label: "Xetitos-Oneulum", value: "roads" },
    { label: "Xetos-Obursum", value: "roads" },
    { label: "Xiles-Aiavlum", value: "roads" },
    { label: "Xilitos-Aoemaum", value: "roads" },
    { label: "Xilos-Osayam", value: "roads" },
    { label: "Xiros-Aiairom", value: "roads" },
    { label: "Xonites-Aiavlum", value: "roads" },
    { label: "Xoritos-Aiairom", value: "roads" },
    { label: "Xoritos-Exostum", value: "roads" },
    { label: "Xoritos-Osayam", value: "roads" },
    { label: "Xouitos-Aeoilos", value: "roads" },
    { label: "Xouitos-Eyoztum", value: "roads" },
    { label: "Xouos-Aioblos", value: "roads" },
    { label: "Xurites-Ataglos", value: "roads" },
    { label: "Xuros-Eyoztum", value: "roads" },
    { label: "Xuyitos-Aioblos", value: "roads" },
    { label: "Xynitos-Obursum", value: "roads" },
    { label: "Xynos-Oyogam", value: "roads" }
];

export const Mapvalues = {
    red: redMapArray,
    blue: blueMapArray,
    roads: roadsMapArray,
    black: blackMapArray,
    yellow: yellowMapArray,
}