import './globals.css';
import './globalAntd.css';
import Loading from './loading';
import { Suspense } from 'react';
import type { Metadata } from 'next';
import { SafeHydrate } from '@/core';
import { Inter } from 'next/font/google';
import { Navbar, SessionProvider } from '@/components';
import { ClientProvider } from '@/core/ApiService/QueryClientConfig';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Albion Guild Tracking',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SafeHydrate>
          <ClientProvider>
            <SessionProvider>
              <Suspense fallback={<Loading />}>
                <Navbar />
                {children}
              </Suspense>
            </SessionProvider>
          </ClientProvider>
        </SafeHydrate>
      </body>
    </html>
  )
}
