import './globals.css'
import type { Metadata } from 'next';
import { SafeHydrate } from '@/Hooks';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Albion Guild Tracking',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SafeHydrate>
          <>
            {children}
          </>
        </SafeHydrate>
      </body>
    </html>
  )
}
